# Nivell 1

## **Exercici 1**: Selecció de Personal

### 🚩 Problema planteado

Tu treballes com a analista de dades en el departament de RRHH d'una empresa. S'ha obert una nova oferta laboral interna i l'empresa ha decidit que només les primeres 10 persones que s'inscriguin podran participar en el procés de selecció.
Per això, t'han encarregat desenvolupar una eina senzilla en Python que actuï com a formulari d'inscripció i sistema de classificació inicial.

Aquest formulari ha de permetre introduir, per a cada candidat/a:
*   Nom i Cognoms
*   Telèfon de contacte
*   Anys d'experiència dins de l'empresa

Coneixement de Català (0–3 punts)
*   0 = sense coneixement
*   1 = fins a nivell B1
*   2 = nivell B2
*   3 = C1 o superior

Domini d'Excel (0–3 punts)
*   0 = nivell bàsic
*   1 = ús de funcions
*   2 = taules dinàmiques
*   3 = Visual Basic i Macros

Títol acadèmic (0–3 punts)
*   0 = ESO
*   1 = FP
*   2 = Universitat
*   3 = Màster o superior

Assegurant-se que tota la informació introduïda és correcta i entra dins els valors permesos. A partir d'aquestes dades, el programa haurà de calcular una puntuació total aplicant el pes de l'experiència (anys * 1.5) i sumant-hi els punts de català, excel i titulació, i a continuació classificar automàticament cada persona segons els llindars establerts per l'empresa:

*   Prioritat Alta → puntuació ≥ 12
*   Candidat adequat → 8 ≤ puntuació < 12
*   No prioritari → puntuació < 8

Cada vegada que algú complet a el formulari, s'ha de mostrar la seva puntuació individual. Quan ja s'hagin inscrit exactament deu persones, l'eina ha de deixar d'acceptar nous registres i generar un informe final en pantalla, ordenat primer segons la prioritat i, en cas d'empat, per la puntuació obtinguda. Aquest informe ha d'incloure el nom, el telèfon i la puntuació de cada candidat per tal que el departament de RRHH els pugui contactar ràpidament.

### 🧠 Análisis y planteamiento del ejercicio

👽 **Planteamiento básico**

1.   Pedir datos al usuario
2.   Comprobar que los años de experiencia son válidos
3.   Evaluar conocimiento de distintas áreas
4.   Pasar respuestas a números enteros
5.   Calcular puntuación total
6.   Clasificar candidatos según resultados
7.   Mostrar resultados
8.   Crear lista de 10 candidatos
9.   Generar informe

💣**Algoritmo planteado**

1.   Pedir datos al usuario `obtener_datos()`
4.   Validar formato de años de experiencia `validar_experiencia()`
3.   Evaluar conocimiento de distintas áreas `nivel_cat()`, `nivel_excel()`, `nivel_estudios()`
4.   Pasar respuestas a números enteros y dentro del rango 0-3 `validar_nivel()`
5.   Calcular puntuacion total (experiencia + conocimientos) `calcular_puntuacion()`
6.   Clasificar candidatos según resultados `asignar_clasificacion()`
7.   Mostrar resultados `mostrar_resultados()`
8.   Crear lista de 10 candidatos `lista_candidatos()`
9.   Generar informe final `generar_informe()`

### 🧩 Desarrollo de funciones

⚡`obtener_datos()`

1. Pedir nombre y apallido y almacena
2. Pedir número de teléfiono y almacenar
3. Pedir años de experiencia y almacenar
4. Devuelve nombre completo, teléfono y experiencia

In [5]:
def obtener_datos():
    nombre_completo = input("Introduce tu primer nombre y primer apellido: ")
    telefono = input("Introduce un teléfono de contacto: ")
    while True:
      experiencia = input("Introduce tus años de experiencia: ")
      experiencia = validar_experiencia(experiencia)
      if experiencia is not None:
          break
    return nombre_completo, telefono, experiencia

⚡`validar_experiencia()`

1. Confirmar la experiencia es un número válido para los calculos posteriores
2. Mostrar mensaje de error si falla algún dato.
3. Almacenar datos correctos.

In [6]:
def validar_experiencia(valor):
    valor = valor.replace(",", ".")
    try:
        valor = float(valor)
        if valor >= 0:
            return valor
        else:
            print("Error: La experiencia no puede ser negativa.")
            return None
    except ValueError:
        print("Error: Por favor, introduce números válidos.")
        return None

In [7]:
# Prueba obtener_datos + validar_experiencia
datos = obtener_datos()

Introduce tu primer nombre y primer apellido: Vanessa Romero
Introduce un teléfono de contacto: 5716005
Introduce tus años de experiencia: 7

⚡`nivel_cat()`

1. Mostrar al usuario las opciones de nivel.
2. Preguntar al usuario su nivel.
3. Almacenar la respuesta en catalan.

In [8]:
def nivel_cat():
    print("Nivel de Catalán:")
    print("  0 = Sin conocimientos")
    print("  1 = Hasta el Nivel B1")
    print("  2 = Nivel B2")
    print("  3 = Nivel C1 o superior")

    catalan = input("Introduce tu Nivel de Catalán (0-3): ")
    return validar_nivel(catalan, 0, 3)

⚡`nivel_excel()`

1. Mostrar al usuario las opciones de nivel.
2. Preguntar al usuario su nivel.
3. Almacenar la respuesta en excel.

In [9]:
def nivel_excel():
    print("Nivel de Excel:")
    print("  0 = Nivel básico")
    print("  1 = Uso de funciones")
    print("  2 = Tablas dinámicas")
    print("  3 = Visual Basic y Macros")

    excel = input("Introduce tu Nivel de Excel (0-3): ")
    return validar_nivel(excel, 0, 3)

⚡`nivel_estudios()`

1. Mostrar al usuario las opciones de nivel.
2. Preguntar al usuario su nivel.
3. Almacenar la respuesta en estudios.

In [10]:
def nivel_estudios():
    print("Título Académico:")
    print("  0 = ESO")
    print("  1 = FP")
    print("  2 = Universidad")
    print("  3 = Máster o Superior")

    estudios = input("Introduce tu Título Académico (0-3): ")
    return validar_nivel(estudios, 0, 3)

⚡`validar_nivel()`

1. Confirmar que el número cumpla las condiciones:
    *   Sea entero
    *   Esté entre 0 y 3
2. Almacenar datos correctos.

In [11]:
def validar_nivel(valor, minimo, maximo):
    try:
        valor = int(valor)
        if minimo <= valor <= maximo:
            return valor
        else:
            return None
    except ValueError:
        return None

In [12]:
# Prueba nivel_cat, nivel_excel, nivel_estudios + validar_nivel
catalan = nivel_cat()
excel = nivel_excel()
estudios = nivel_estudios()

Nivel de Catalán:
  0 = Sin conocimientos
  1 = Hasta el Nivel B1
  2 = Nivel B2
  3 = Nivel C1 o superior
Introduce tu Nivel de Catalán (0-3): 3
Nivel de Excel:
  0 = Nivel básico
  1 = Uso de funciones
  2 = Tablas dinámicas
  3 = Visual Basic y Macros
Introduce tu Nivel de Excel (0-3): 3
Título Académico:
  0 = ESO
  1 = FP
  2 = Universidad
  3 = Máster o Superior
Introduce tu Título Académico (0-3): 3

⚡`calcular_puntuacion()`

1. Multiplicar los años de experiencia por 1.5.
2. Sumar los puntos de los distintos niveles evaluados.
3. Almacenar el resultado total como `float`.

In [13]:
def calcular_puntuacion(valor, num1, num2, num3):
    experiencia = valor * 1.5
    conocimiento = num1 + num2 + num3
    puntuacion = experiencia + conocimiento
    return float(puntuacion)

In [14]:
# Prueba calcular_puntuacion
puntuacion = calcular_puntuacion(7, 0, 2, 3)
print(puntuacion)

15.5

⚡`asignar_clasificacion()`

1. Asignar valores a cada rango de puntuacion.
2. Almacenar resultados por grupo.

In [15]:
def asignar_clasificacion(valor):
    match valor:
        case alto if alto >= 12:
            return "Prioridad Alta"
        case medio if 8 <= medio < 12:
            return "Candidato/a adecuado/a"
        case bajo:
            return "No prioritario/a"

In [16]:
# Prueba asignar_clasificacion
clasificacion = asignar_clasificacion(15.5)
print(clasificacion)

Prioridad Alta

⚡`mostrar_resultados()`

1. Mostrar al usuario la puntuación obtenida.

In [17]:
def mostrar_resultados(nombre_completo, valor):
    print(f"Gracias por inscribirte {nombre_completo}, tu puntuación como candidato es {valor}")
    print("\n")

In [18]:
# Prueba mostrar_resultados
resultados = mostrar_resultados("Vanessa Romero", 15.5)

Gracias por inscribirte Vanessa Romero, tu puntuación como candidato es 15.5

⚡`lista_candidatos()`

1. Crear una lista con la información de los candidatos
2. Bloquear lista de candidatos cuando llegue a 10
3. Añadir cada diccionario a la lista candidatos

In [19]:
def lista_candidatos():
    candidatos = []

    while len(candidatos) < 10:
        nombre_completo, telefono, experiencia = obtener_datos()
        cat = nivel_cat()
        exc = nivel_excel()
        est = nivel_estudios()

        if None in (experiencia, cat, exc, est):
            print("Registro descartado por datos incorrectos. Vuelve a intentarlo")
            print("\n")
            continue

        puntuacion = calcular_puntuacion(experiencia, cat, exc, est)
        clasificacion = asignar_clasificacion(puntuacion)
        mostrar_resultados(nombre_completo, puntuacion)

        candidato = {
            "nombre": nombre_completo,
            "telefono": telefono,
            "puntuacion": puntuacion,
            "clasificacion": clasificacion
        }
        candidatos.append(candidato)

    print("\n🚫 Inscripciones cerradas. Se han registrado 10 candidatos.")

    return candidatos

⚡`generar_informe()`

1. Ordenar lista de candidatos
2. Mostrar los candidatos ordenados

In [20]:
def generar_informe(candidatos):
    orden_prioridad = {
        "Prioridad Alta": 1,
        "Candidato/a adecuado/a": 2,
        "No prioritario/a": 3
    }

    candidatos_ordenados = sorted(
        candidatos,
        key=lambda c: (orden_prioridad[c["clasificacion"]], -c["puntuacion"])
    )

    print("\n===== INFORME FINAL DE CANDIDATOS =====")
    for candidato in candidatos_ordenados:
        print(f"Nombre: {candidato['nombre']}")
        print(f"Teléfono: {candidato['telefono']}")
        print(f"Puntuación: {candidato['puntuacion']}")
        print(f"Clasificación: {candidato['clasificacion']}")
        print("---------------------------------------")

### 🏆 Resultado final (INTEGRAR)

In [21]:
# Creación de lista de candidatos y generación de informe final
resultado_seleccion_person = generar_informe(lista_candidatos())

Introduce tu primer nombre y primer apellido: Laura Serra
Introduce un teléfono de contacto: 608112233
Introduce tus años de experiencia: 6
Nivel de Catalán:
  0 = Sin conocimientos
  1 = Hasta el Nivel B1
  2 = Nivel B2
  3 = Nivel C1 o superior
Introduce tu Nivel de Catalán (0-3): 3
Nivel de Excel:
  0 = Nivel básico
  1 = Uso de funciones
  2 = Tablas dinámicas
  3 = Visual Basic y Macros
Introduce tu Nivel de Excel (0-3): 3
Título Académico:
  0 = ESO
  1 = FP
  2 = Universidad
  3 = Máster o Superior
Introduce tu Título Académico (0-3): 3
Gracias por inscribirte Laura Serra, tu puntuación como candidato es 18.0


Introduce tu primer nombre y primer apellido: Clara Gómez
Introduce un teléfono de contacto: 655221199
Introduce tus años de experiencia: 3
Nivel de Catalán:
  0 = Sin conocimientos
  1 = Hasta el Nivel B1
  2 = Nivel B2
  3 = Nivel C1 o superior
Introduce tu Nivel de Catalán (0-3): 3
Nivel de Excel:
  0 = Nivel básico
  1 = Uso de funciones
  2 = Tablas dinámicas
  3 = Visual Basic y Macros
Introduce tu Nivel de Excel (0-3): 3
Título Académico:
  0 = ESO
  1 = FP
  2 = Universidad
  3 = Máster o Superior
Introduce tu Título Académico (0-3): 2
Gracias por inscribirte Clara Gómez, tu puntuación como candidato es 12.5


Introduce tu primer nombre y primer apellido: Sergio López
Introduce un teléfono de contacto: 644112211
Introduce tus años de experiencia: 3
Nivel de Catalán:
  0 = Sin conocimientos
  1 = Hasta el Nivel B1
  2 = Nivel B2
  3 = Nivel C1 o superior
Introduce tu Nivel de Catalán (0-3): 2
Nivel de Excel:
  0 = Nivel básico
  1 = Uso de funciones
  2 = Tablas dinámicas
  3 = Visual Basic y Macros
Introduce tu Nivel de Excel (0-3): 2
Título Académico:
  0 = ESO
  1 = FP
  2 = Universidad
  3 = Máster o Superior
Introduce tu Título Académico (0-3): 2
Gracias por inscribirte Sergio López, tu puntuación como candidato es 10.5


Introduce tu primer nombre y primer apellido: Candidat Error
Introduce un teléfono de contacto: 611000000
Introduce tus años de experiencia: 7
Nivel de Catalán:
  0 = Sin conocimientos
  1 = Hasta el Nivel B1
  2 = Nivel B2
  3 = Nivel C1 o superior
Introduce tu Nivel de Catalán (0-3): 5
Nivel de Excel:
  0 = Nivel básico
  1 = Uso de funciones
  2 = Tablas dinámicas
  3 = Visual Basic y Macros
Introduce tu Nivel de Excel (0-3): 3
Título Académico:
  0 = ESO
  1 = FP
  2 = Universidad
  3 = Máster o Superior
Introduce tu Título Académico (0-3): 2
Registro descartado por datos incorrectos. Vuelve a intentarlo


Introduce tu primer nombre y primer apellido: Marta Ruz
Introduce un teléfono de contacto: 699887766
Introduce tus años de experiencia: 2
Nivel de Catalán:
  0 = Sin conocimientos
  1 = Hasta el Nivel B1
  2 = Nivel B2
  3 = Nivel C1 o superior
Introduce tu Nivel de Catalán (0-3): 3
Nivel de Excel:
  0 = Nivel básico
  1 = Uso de funciones
  2 = Tablas dinámicas
  3 = Visual Basic y Macros
Introduce tu Nivel de Excel (0-3): 2
Título Académico:
  0 = ESO
  1 = FP
  2 = Universidad
  3 = Máster o Superior
Introduce tu Título Académico (0-3): 1
Gracias por inscribirte Marta Ruz, tu puntuación como candidato es 9.0


Introduce tu primer nombre y primer apellido: Marc Vidal
Introduce un teléfono de contacto: 612443322
Introduce tus años de experiencia: 6
Nivel de Catalán:
  0 = Sin conocimientos
  1 = Hasta el Nivel B1
  2 = Nivel B2
  3 = Nivel C1 o superior
Introduce tu Nivel de Catalán (0-3): 3
Nivel de Excel:
  0 = Nivel básico
  1 = Uso de funciones
  2 = Tablas dinámicas
  3 = Visual Basic y Macros
Introduce tu Nivel de Excel (0-3): 3
Título Académico:
  0 = ESO
  1 = FP
  2 = Universidad
  3 = Máster o Superior
Introduce tu Título Académico (0-3): 3
Gracias por inscribirte Marc Vidal, tu puntuación como candidato es 18.0


Introduce tu primer nombre y primer apellido: Júlia Romero
Introduce un teléfono de contacto: 677998877
Introduce tus años de experiencia: 5
Nivel de Catalán:
  0 = Sin conocimientos
  1 = Hasta el Nivel B1
  2 = Nivel B2
  3 = Nivel C1 o superior
Introduce tu Nivel de Catalán (0-3): 3
Nivel de Excel:
  0 = Nivel básico
  1 = Uso de funciones
  2 = Tablas dinámicas
  3 = Visual Basic y Macros
Introduce tu Nivel de Excel (0-3): 3
Título Académico:
  0 = ESO
  1 = FP
  2 = Universidad
  3 = Máster o Superior
Introduce tu Título Académico (0-3): 2
Gracias por inscribirte Júlia Romero, tu puntuación como candidato es 15.5


Introduce tu primer nombre y primer apellido: Pol Navarro
Introduce un teléfono de contacto: 699554433
Introduce tus años de experiencia: 4
Nivel de Catalán:
  0 = Sin conocimientos
  1 = Hasta el Nivel B1
  2 = Nivel B2
  3 = Nivel C1 o superior
Introduce tu Nivel de Catalán (0-3): 3
Nivel de Excel:
  0 = Nivel básico
  1 = Uso de funciones
  2 = Tablas dinámicas
  3 = Visual Basic y Macros
Introduce tu Nivel de Excel (0-3): 2
Título Académico:
  0 = ESO
  1 = FP
  2 = Universidad
  3 = Máster o Superior
Introduce tu Título Académico (0-3): 2
Gracias por inscribirte Pol Navarro, tu puntuación como candidato es 13.0


Introduce tu primer nombre y primer apellido: David Ferrer
Introduce un teléfono de contacto: 677665544
Introduce tus años de experiencia: 2
Nivel de Catalán:
  0 = Sin conocimientos
  1 = Hasta el Nivel B1
  2 = Nivel B2
  3 = Nivel C1 o superior
Introduce tu Nivel de Catalán (0-3): 1
Nivel de Excel:
  0 = Nivel básico
  1 = Uso de funciones
  2 = Tablas dinámicas
  3 = Visual Basic y Macros
Introduce tu Nivel de Excel (0-3): 1
Título Académico:
  0 = ESO
  1 = FP
  2 = Universidad
  3 = Máster o Superior
Introduce tu Título Académico (0-3): 1
Gracias por inscribirte David Ferrer, tu puntuación como candidato es 6.0


Introduce tu primer nombre y primer apellido: Anna Paredes
Introduce un teléfono de contacto: 633221144
Introduce tus años de experiencia: 1
Nivel de Catalán:
  0 = Sin conocimientos
  1 = Hasta el Nivel B1
  2 = Nivel B2
  3 = Nivel C1 o superior
Introduce tu Nivel de Catalán (0-3): 2
Nivel de Excel:
  0 = Nivel básico
  1 = Uso de funciones
  2 = Tablas dinámicas
  3 = Visual Basic y Macros
Introduce tu Nivel de Excel (0-3): 1
Título Académico:
  0 = ESO
  1 = FP
  2 = Universidad
  3 = Máster o Superior
Introduce tu Título Académico (0-3): 0
Gracias por inscribirte Anna Paredes, tu puntuación como candidato es 4.5


Introduce tu primer nombre y primer apellido: Anibal Paredes
Introduce un teléfono de contacto: 644272727
Introduce tus años de experiencia: 1
Nivel de Catalán:
  0 = Sin conocimientos
  1 = Hasta el Nivel B1
  2 = Nivel B2
  3 = Nivel C1 o superior
Introduce tu Nivel de Catalán (0-3): 2
Nivel de Excel:
  0 = Nivel básico
  1 = Uso de funciones
  2 = Tablas dinámicas
  3 = Visual Basic y Macros
Introduce tu Nivel de Excel (0-3): 1
Título Académico:
  0 = ESO
  1 = FP
  2 = Universidad
  3 = Máster o Superior
Introduce tu Título Académico (0-3): 0
Gracias por inscribirte Anibal Paredes, tu puntuación como candidato es 4.5



🚫 Inscripciones cerradas. Se han registrado 10 candidatos.

===== INFORME FINAL DE CANDIDATOS =====
Nombre: Laura Serra
Teléfono: 608112233
Puntuación: 18.0
Clasificación: Prioridad Alta
---------------------------------------
Nombre: Marc Vidal
Teléfono: 612443322
Puntuación: 18.0
Clasificación: Prioridad Alta
---------------------------------------
Nombre: Júlia Romero
Teléfono: 677998877
Puntuación: 15.5
Clasificación: Prioridad Alta
---------------------------------------
Nombre: Pol Navarro
Teléfono: 699554433
Puntuación: 13.0
Clasificación: Prioridad Alta
---------------------------------------
Nombre: Clara Gómez
Teléfono: 655221199
Puntuación: 12.5
Clasificación: Prioridad Alta
---------------------------------------
Nombre: Sergio López
Teléfono: 644112211
Puntuación: 10.5
Clasificación: Candidato/a adecuado/a
---------------------------------------
Nombre: Marta Ruz
Teléfono: 699887766
Puntuación: 9.0
Clasificación: Candidato/a adecuado/a
---------------------------------------
Nombre: David Ferrer
Teléfono: 677665544
Puntuación: 6.0
Clasificación: No prioritario/a
---------------------------------------
Nombre: Anna Paredes
Teléfono: 633221144
Puntuación: 4.5
Clasificación: No prioritario/a
---------------------------------------
Nombre: Anibal Paredes
Teléfono: 644272727
Puntuación: 4.5
Clasificación: No prioritario/a
---------------------------------------

### 📝 Notas sobre el ejercicio

*   Debido al planteamiento de las funciones `obtener_datos()` y `nivel_X()`, su comprobación no se realiza inmediatamente después de definirlas, ya que dependen de funciones de validación asociadas. Por este motivo, se comprueba su funcionamiento de forma conjunta una vez definidas dichas funciones de validación.  
*   En un primer planteamiento se consideró utilizar `while` tanto para validar los años de experiencia como los niveles introducidos, con el objetivo de obligar al usuario a introducir datos válidos. Finalmente, se descartó esta opción al revisar la estructura y el tipo de datos requeridos en el ejercicio.
*   No se añadieron validaciones adicionales para otros campos, como por ejemplo el número de teléfono, ya que el enunciado no lo solicitaba de forma explícita. No obstante, estas validaciones podrían haberse incorporado.

## **Exercici 2**: Segmentació per risc de cistella de compra

### 🚩 Problema planteado

Treballes com a analista de dades al departament de Màrqueting Digital. L'empresa vol millorar l'efectivitat de les campanyes de recuperació de cistellas de compra abandonats i necessita identificar quins clients tenen més risc d'abandonament, quin segment de comportament presenten i quin missatge publicitari és el més adequat per a cadascun.

Disposes d'un conjunt de dades amb informació bàsica de 10 clients:

- id_client
- nom
- edat
- grup_edat
- codi_comportament
                
<br>

El departament de CRM ha definit manualment:

Codis de comportament
*   0 → Navega però no afegeix productes
*   1 → Afegeix productes però no arriba al checkout
*   2 → Arriba al checkout però no paga
*   3 → Cistella de compra abandonat fa menys de 24 h
*   4 → Cistella de compra abandonat fa més de 24 h

Factors segons codi de comportament
*   Codi 0 → 0.10
*   Codi 1 → 0.25
*   Codi 2 → 0.50
*   Codi 3 → 0.75
*   Codi 4 → 0.90

Factors segons grup d'edat
*   18–25 → 1.20
*   26–40 → 1.00
*   41–60 → 0.85
*   60+ → 0.70

Fórmula del risc final
*   risc_final = factor codi * factor edat

<br>

Un cop processats els clients, has de ser capaç de respondre:

1. Quins clients s'han de contactar primer en una campanya de retargeting?
2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents? (Per exemple: un client jove que abandona la cistella de compra fa 24 h té el mateix risc que un de més edat?)
3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?
4. Quin client seria el més rendible de recuperar?
Interpretant el risc final i el segment.

<br>

⚙️ Requisits tècnics del teu programa
*   Hauràs de construir un sistema modular utilitzant diverses funcions i, sobretot, sense utilitzar if/elif/else per fer la segmentació.

### 🧠 Análisis y planteamiento del ejercicio

👽 **Planteamiento básico**

1.   Crear la lista de clientes con los datos
2.   Asignar factor a clientes según código de comportamiento
3.   Asignar factor de edad a clientes
4.   Calcular riesgo
5.   Evaluar clientes según sus datos
6.   Crear un diccionario con los clientes evaluados
7.   Hacer los distintos análisis para responder las preguntas de marketing
8.   Interpretar y mostrar los resultados de cada pregunta.
9.   Crear una función final de consulta para Marketing

💣**Algoritmo planteado**

1. Crear la lista de clientes con los datos del ejercicio.

2. Obtener segmento, mensaje y factor según el código de comportamiento `obtener_segmento_factor()`

    Consultar el código de comportamiento del cliente y devolver el segmento, el mensaje asociado y el factor correspondiente.

3. Obtener factor edad `obtener_factor_edad()`

    A partir del grupo de edad del cliente, consultar y devolver el factor de edad correspondiente.

4. Calcular el riesgo final `calcular_riesgo()`

    Calcular el riesgo final de cada cliente multiplicando el factor de comportamiento por el factor de edad.

5. Procesar la información de los clientes `procesar_clientes()`

    Recorrer la lista de clientes y utilizar las funciones anteriores para completar la información de cada uno con su segmento, mensaje, factores y riesgo final.

6. Mostrar los clientes procesados `mostrar_diccionario()`

    Mostrar de forma ordenada el diccionario final con toda la información original y los nuevos datos obtenidos durante el procesamiento.

7. Ejecutar distintos análisis que permitan responder las preguntas del departamento de marketing y asignar los datos a variables especificas.

8. Interpretar y mostrar los resultados de cada pregunta

    Utilizar los datos de los clientes procesados para obtener la información necesaria para responder a las preguntas planteadas por el departamento de Marketing.

9. Ejecutar el programa completo `main_marketing()`

    Coordinar la ejecución de las diferentes funciones y mostrar tanto los clientes procesados como los resultados del análisis.

### 🧩 Desarrollo de funciones

In [ ]:
# Creaer lista_clientes
lista_clientes = [
    {"id_client": 1, "nom": "Laura Serra", "edat": 23, "grup_edat": "18-25", "codi_comportament": 4},
    {"id_client": 2, "nom": "Marc Vidal", "edat": 35, "grup_edat": "26-40", "codi_comportament": 3},
    {"id_client": 3, "nom": "Ana López", "edat": 29, "grup_edat": "26-40", "codi_comportament": 2},
    {"id_client": 4, "nom": "Joan Riera", "edat": 19, "grup_edat": "18-25", "codi_comportament": 2},
    {"id_client": 5, "nom": "Mónica Pérez", "edat": 47, "grup_edat": "41-60", "codi_comportament": 4},
    {"id_client": 6, "nom": "Luis García", "edat": 52, "grup_edat": "41-60", "codi_comportament": 1},
    {"id_client": 7, "nom": "Pilar Sánchez", "edat": 61, "grup_edat": "60+", "codi_comportament": 3},
    {"id_client": 8, "nom": "Eva Martín", "edat": 38, "grup_edat": "26-40", "codi_comportament": 0},
    {"id_client": 9, "nom": "Diego Romero", "edat": 24, "grup_edat": "18-25", "codi_comportament": 1},
    {"id_client": 10, "nom": "Núria Costa", "edat": 33, "grup_edat": "26-40", "codi_comportament": 4}
]

⚡`obtener_segmento_factor()`

1. Recibir el código de comportamiento de un cliente.
2. Asignar factor de comportamiento asociado.
3. Asignar mensaje asociado.
4. Devolver factor y mensaje.

In [ ]:
def obtener_segmento_factor(codigo_comportamiento):
    segmento = {
        0: {"factor": 0.10, "missatge": "Navega però no afegeix productes"},
        1: {"factor": 0.25, "missatge": "Afegeix productes però no arriba al checkout"},
        2: {"factor": 0.50, "missatge": "Arriba al checkout però no paga"},
        3: {"factor": 0.75, "missatge": "Cistella abandonat fa menys de 24h"},
        4: {"factor": 0.90, "missatge": "Cistella abandonat fa més de 24h"}
    }

    return segmento[codigo_comportamiento]

In [ ]:
# Prueba obtener_segmento_factor
segmento = obtener_segmento_factor(0)
print(segmento)

{'factor': 0.1, 'missatge': 'Navega però no afegeix productes'}

⚡`obtener_factor_edad()`

1. Recibir el grupo de edad del cliente
2. Asignar factor de edad asociado
3. Devolver factor

In [ ]:
def obtener_factor_edad(grupo_edad):
    factor = {
        "18-25": 1.20,
        "26-40": 1.00,
        "41-60": 0.85,
        "60+": 0.70
    }
    return factor[grupo_edad]

In [ ]:
# Prueba obtener_factor_edad
factor_edad = obtener_factor_edad("41-60")
print(factor_edad)

0.85

⚡`calcular_riesgo()`

1. Recibir el factor de comportamiento del cliente
2. Recibir el factor de edad del cliente
3. Aplicar la operación matemática.
4. Devolver el valor de riesgo.

In [ ]:
def calcular_riesgo(comportamiento, edad):
  calculo = float(comportamiento) * float(edad)
  return round(calculo, 2)

In [ ]:
# Prueba calcular_riesgo
riesgo = calcular_riesgo(0.1, 0.85)
print(riesgo)

0.09

⚡`procesar_clientes()`

1. Recibir datos del cliente.
2. Asignar código de comportamiento y mensaje.
3. Asignar factor de edad.
4. Hacer calculo de riesgo.

In [ ]:
def procesar_clientes(lista_clientes):
    resultado = {}

    for cliente in lista_clientes:
        segmento = obtener_segmento_factor(cliente["codi_comportament"])
        factor_edad = obtener_factor_edad(cliente["grup_edat"])
        riesgo = calcular_riesgo(segmento["factor"], factor_edad)

        resultado[cliente["id_client"]] = {
            "nom": cliente["nom"],
            "edat": cliente["edat"],
            "grup_edat": cliente["grup_edat"],
            "codi_comportament": cliente["codi_comportament"],
            "missatge": segmento["missatge"],
            "factor_codi": segmento["factor"],
            "factor_edat": factor_edad,
            "risc_final": riesgo
        }

    return resultado

In [ ]:
# Prueba procesar_clientes
from pprint import pprint

clientes_procesados = procesar_clientes(lista_clientes)
pprint(clientes_procesados, sort_dicts=False)

{1: {'nom': 'Laura Serra',
     'edat': 23,
     'grup_edat': '18-25',
     'codi_comportament': 4,
     'missatge': 'Cistella abandonat fa més de 24h',
     'factor_codi': 0.9,
     'factor_edat': 1.2,
     'risc_final': 1.08},
 2: {'nom': 'Marc Vidal',
     'edat': 35,
     'grup_edat': '26-40',
     'codi_comportament': 3,
     'missatge': 'Cistella abandonat fa menys de 24h',
     'factor_codi': 0.75,
     'factor_edat': 1.0,
     'risc_final': 0.75},
 3: {'nom': 'Ana López',
     'edat': 29,
     'grup_edat': '26-40',
     'codi_comportament': 2,
     'missatge': 'Arriba al checkout però no paga',
     'factor_codi': 0.5,
     'factor_edat': 1.0,
     'risc_final': 0.5},
 4: {'nom': 'Joan Riera',
     'edat': 19,
     'grup_edat': '18-25',
     'codi_comportament': 2,
     'missatge': 'Arriba al checkout però no paga',
     'factor_codi': 0.5,
     'factor_edat': 1.2,
     'risc_final': 0.6},
 5: {'nom': 'Mónica Pérez',
     'edat': 47,
     'grup_edat': '41-60',
     'codi_comportament': 4,
     'missatge': 'Cistella abandonat fa més de 24h',
     'factor_codi': 0.9,
     'factor_edat': 0.85,
     'risc_final': 0.77},
 6: {'nom': 'Luis García',
     'edat': 52,
     'grup_edat': '41-60',
     'codi_comportament': 1,
     'missatge': 'Afegeix productes però no arriba al checkout',
     'factor_codi': 0.25,
     'factor_edat': 0.85,
     'risc_final': 0.21},
 7: {'nom': 'Pilar Sánchez',
     'edat': 61,
     'grup_edat': '60+',
     'codi_comportament': 3,
     'missatge': 'Cistella abandonat fa menys de 24h',
     'factor_codi': 0.75,
     'factor_edat': 0.7,
     'risc_final': 0.52},
 8: {'nom': 'Eva Martín',
     'edat': 38,
     'grup_edat': '26-40',
     'codi_comportament': 0,
     'missatge': 'Navega però no afegeix productes',
     'factor_codi': 0.1,
     'factor_edat': 1.0,
     'risc_final': 0.1},
 9: {'nom': 'Diego Romero',
     'edat': 24,
     'grup_edat': '18-25',
     'codi_comportament': 1,
     'missatge': 'Afegeix productes però no arriba al checkout',
     'factor_codi': 0.25,
     'factor_edat': 1.2,
     'risc_final': 0.3},
 10: {'nom': 'Núria Costa',
      'edat': 33,
      'grup_edat': '26-40',
      'codi_comportament': 4,
      'missatge': 'Cistella abandonat fa més de 24h',
      'factor_codi': 0.9,
      'factor_edat': 1.0,
      'risc_final': 0.9}}

⚡`mostrar_diccionario()`

1. Recibir el diccionario de clientes procesados
2. Formatear las líneas con cada dato del diccionario
3. Mostrar el diccionario

In [ ]:
def mostrar_diccionario(clientes_procesados):
    for id_client, datos in clientes_procesados.items():
        print(f"--- Cliente {id_client} ---")
        print(f"Nom: {datos['nom']}")
        print(f"Edat: {datos['edat']}")
        print(f"Grup edat: {datos['grup_edat']}")
        print(f"Comportament: {datos['codi_comportament']}")
        print(f"Missatge: {datos['missatge']}")
        print(f"Factor codi: {datos['factor_codi']}")
        print(f"Factor edat: {datos['factor_edat']}")
        print(f"Risc final: {datos['risc_final']}")
        print()

In [ ]:
# Prueba mostrar_diccionario

diccionario_ordenado = mostrar_diccionario(clientes_procesados)

--- Cliente 1 ---
Nom: Laura Serra
Edat: 23
Grup edat: 18-25
Comportament: 4
Missatge: Cistella abandonat fa més de 24h
Factor codi: 0.9
Factor edat: 1.2
Risc final: 1.08

--- Cliente 2 ---
Nom: Marc Vidal
Edat: 35
Grup edat: 26-40
Comportament: 3
Missatge: Cistella abandonat fa menys de 24h
Factor codi: 0.75
Factor edat: 1.0
Risc final: 0.75

--- Cliente 3 ---
Nom: Ana López
Edat: 29
Grup edat: 26-40
Comportament: 2
Missatge: Arriba al checkout però no paga
Factor codi: 0.5
Factor edat: 1.0
Risc final: 0.5

--- Cliente 4 ---
Nom: Joan Riera
Edat: 19
Grup edat: 18-25
Comportament: 2
Missatge: Arriba al checkout però no paga
Factor codi: 0.5
Factor edat: 1.2
Risc final: 0.6

--- Cliente 5 ---
Nom: Mónica Pérez
Edat: 47
Grup edat: 41-60
Comportament: 4
Missatge: Cistella abandonat fa més de 24h
Factor codi: 0.9
Factor edat: 0.85
Risc final: 0.77

--- Cliente 6 ---
Nom: Luis García
Edat: 52
Grup edat: 41-60
Comportament: 1
Missatge: Afegeix productes però no arriba al checkout
Factor codi: 0.25
Factor edat: 0.85
Risc final: 0.21

--- Cliente 7 ---
Nom: Pilar Sánchez
Edat: 61
Grup edat: 60+
Comportament: 3
Missatge: Cistella abandonat fa menys de 24h
Factor codi: 0.75
Factor edat: 0.7
Risc final: 0.52

--- Cliente 8 ---
Nom: Eva Martín
Edat: 38
Grup edat: 26-40
Comportament: 0
Missatge: Navega però no afegeix productes
Factor codi: 0.1
Factor edat: 1.0
Risc final: 0.1

--- Cliente 9 ---
Nom: Diego Romero
Edat: 24
Grup edat: 18-25
Comportament: 1
Missatge: Afegeix productes però no arriba al checkout
Factor codi: 0.25
Factor edat: 1.2
Risc final: 0.3

--- Cliente 10 ---
Nom: Núria Costa
Edat: 33
Grup edat: 26-40
Comportament: 4
Missatge: Cistella abandonat fa més de 24h
Factor codi: 0.9
Factor edat: 1.0
Risc final: 0.9

⚡`main_marketing()`

1. Hacer print de un título individual por cada pregunta
2. Mostrar los resultados previamente calculados para las cuatro preguntas de Marketing

In [ ]:
def main_marketing():

    print("PREGUNTA 1:", " ", "Clients per campanya de retargeting")
    mostrar_diccionario(pregunta_1)

    print("PREGUNTA 2:", " ", "Clients amb el mateix comportament")
    for codigo, clientes_grupo in pregunta_2.items():
        print(f"\n--- Comportament {codigo} ---")
        mostrar_diccionario(clientes_grupo)

    print("PREGUNTA 3:", " ", "Clients amb poc interès")
    mostrar_diccionario(pregunta_3)

    print("PREGUNTA 4:", " ", "Clients més rendibles de recuperar")
    mostrar_diccionario(pregunta_4)

### Análisis para responder las preguntas de marketing

In [ ]:
# Pregunta 1
# Clientes para la campaña de retargeting

pregunta_1 = dict(sorted(
    clientes_procesados.items(),
    key=lambda cliente: cliente[1]["risc_final"],
    reverse=True
))

In [ ]:
# Pregunta 2
# Clients amb el mateix comportament però d'edats diferents

pregunta_2 = {}

for id_cliente, cliente in clientes_procesados.items():
    codigo = cliente["codi_comportament"]

    if codigo not in pregunta_2:
        pregunta_2[codigo] = {}

    pregunta_2[codigo][id_cliente] = cliente

In [ ]:
# Pregunta 3
# Clients amb poc interès

pregunta_3 = {}

for id_cliente, cliente in clientes_procesados.items():
    if cliente["codi_comportament"] == 0:
        pregunta_3[id_cliente] = cliente

In [ ]:
# Pregunta 4
# Client més rendible de recuperar

pregunta_4 = {}

for id_cliente, cliente in pregunta_1.items():
    if cliente["codi_comportament"] in [2, 3]:
        pregunta_4[id_cliente] = cliente
        break

### 🏆 Resultado final

**Pregunta 1**: Los clientes con mayor `risc_final` deberían ser contactados primero porque combinan un comportamiento de abandono avanzado con un factor de edad que aumenta su riesgo.

**Pregunta 2**: Se agrupan los clientes por `codi_comportament` para comparar a aquellos que presentan el mismo comportamiento y analizar cómo varía su `risc_final` según la edad.

**Pregunta 3**: Se filtran los clientes con `codi_comportament 0`, ya que corresponden al segmento con menor interés al navegar sin llegar a añadir productos.

**Pregunta 4**: Se utilizan los clientes ya ordenados por `risc_final` y se filtran los segmentos 2 y 3. Se selecciona el primer cliente que cumple esta condición, ya que será el de mayor riesgo dentro de estos segmentos.

In [ ]:
#Pregunta 1
mostrar_diccionario(pregunta_1)

--- Cliente 1 ---
Nom: Laura Serra
Edat: 23
Grup edat: 18-25
Comportament: 4
Missatge: Cistella abandonat fa més de 24h
Factor codi: 0.9
Factor edat: 1.2
Risc final: 1.08

--- Cliente 10 ---
Nom: Núria Costa
Edat: 33
Grup edat: 26-40
Comportament: 4
Missatge: Cistella abandonat fa més de 24h
Factor codi: 0.9
Factor edat: 1.0
Risc final: 0.9

--- Cliente 5 ---
Nom: Mónica Pérez
Edat: 47
Grup edat: 41-60
Comportament: 4
Missatge: Cistella abandonat fa més de 24h
Factor codi: 0.9
Factor edat: 0.85
Risc final: 0.77

--- Cliente 2 ---
Nom: Marc Vidal
Edat: 35
Grup edat: 26-40
Comportament: 3
Missatge: Cistella abandonat fa menys de 24h
Factor codi: 0.75
Factor edat: 1.0
Risc final: 0.75

--- Cliente 4 ---
Nom: Joan Riera
Edat: 19
Grup edat: 18-25
Comportament: 2
Missatge: Arriba al checkout però no paga
Factor codi: 0.5
Factor edat: 1.2
Risc final: 0.6

--- Cliente 7 ---
Nom: Pilar Sánchez
Edat: 61
Grup edat: 60+
Comportament: 3
Missatge: Cistella abandonat fa menys de 24h
Factor codi: 0.75
Factor edat: 0.7
Risc final: 0.52

--- Cliente 3 ---
Nom: Ana López
Edat: 29
Grup edat: 26-40
Comportament: 2
Missatge: Arriba al checkout però no paga
Factor codi: 0.5
Factor edat: 1.0
Risc final: 0.5

--- Cliente 9 ---
Nom: Diego Romero
Edat: 24
Grup edat: 18-25
Comportament: 1
Missatge: Afegeix productes però no arriba al checkout
Factor codi: 0.25
Factor edat: 1.2
Risc final: 0.3

--- Cliente 6 ---
Nom: Luis García
Edat: 52
Grup edat: 41-60
Comportament: 1
Missatge: Afegeix productes però no arriba al checkout
Factor codi: 0.25
Factor edat: 0.85
Risc final: 0.21

--- Cliente 8 ---
Nom: Eva Martín
Edat: 38
Grup edat: 26-40
Comportament: 0
Missatge: Navega però no afegeix productes
Factor codi: 0.1
Factor edat: 1.0
Risc final: 0.1

In [ ]:
# Pregunta 2
for codigo, clientes in pregunta_2.items():
    print(f"\n--- Comportament {codigo} ---")
    mostrar_diccionario(clientes)

--- Comportament 4 ---
--- Cliente 1 ---
Nom: Laura Serra
Edat: 23
Grup edat: 18-25
Comportament: 4
Missatge: Cistella abandonat fa més de 24h
Factor codi: 0.9
Factor edat: 1.2
Risc final: 1.08

--- Cliente 5 ---
Nom: Mónica Pérez
Edat: 47
Grup edat: 41-60
Comportament: 4
Missatge: Cistella abandonat fa més de 24h
Factor codi: 0.9
Factor edat: 0.85
Risc final: 0.77

--- Cliente 10 ---
Nom: Núria Costa
Edat: 33
Grup edat: 26-40
Comportament: 4
Missatge: Cistella abandonat fa més de 24h
Factor codi: 0.9
Factor edat: 1.0
Risc final: 0.9


--- Comportament 3 ---
--- Cliente 2 ---
Nom: Marc Vidal
Edat: 35
Grup edat: 26-40
Comportament: 3
Missatge: Cistella abandonat fa menys de 24h
Factor codi: 0.75
Factor edat: 1.0
Risc final: 0.75

--- Cliente 7 ---
Nom: Pilar Sánchez
Edat: 61
Grup edat: 60+
Comportament: 3
Missatge: Cistella abandonat fa menys de 24h
Factor codi: 0.75
Factor edat: 0.7
Risc final: 0.52


--- Comportament 2 ---
--- Cliente 3 ---
Nom: Ana López
Edat: 29
Grup edat: 26-40
Comportament: 2
Missatge: Arriba al checkout però no paga
Factor codi: 0.5
Factor edat: 1.0
Risc final: 0.5

--- Cliente 4 ---
Nom: Joan Riera
Edat: 19
Grup edat: 18-25
Comportament: 2
Missatge: Arriba al checkout però no paga
Factor codi: 0.5
Factor edat: 1.2
Risc final: 0.6


--- Comportament 1 ---
--- Cliente 6 ---
Nom: Luis García
Edat: 52
Grup edat: 41-60
Comportament: 1
Missatge: Afegeix productes però no arriba al checkout
Factor codi: 0.25
Factor edat: 0.85
Risc final: 0.21

--- Cliente 9 ---
Nom: Diego Romero
Edat: 24
Grup edat: 18-25
Comportament: 1
Missatge: Afegeix productes però no arriba al checkout
Factor codi: 0.25
Factor edat: 1.2
Risc final: 0.3


--- Comportament 0 ---
--- Cliente 8 ---
Nom: Eva Martín
Edat: 38
Grup edat: 26-40
Comportament: 0
Missatge: Navega però no afegeix productes
Factor codi: 0.1
Factor edat: 1.0
Risc final: 0.1

In [ ]:
# Pregunta 3
mostrar_diccionario(pregunta_3)

--- Cliente 8 ---
Nom: Eva Martín
Edat: 38
Grup edat: 26-40
Comportament: 0
Missatge: Navega però no afegeix productes
Factor codi: 0.1
Factor edat: 1.0
Risc final: 0.1

In [ ]:
# Pregunta 4
mostrar_diccionario(pregunta_4)

--- Cliente 2 ---
Nom: Marc Vidal
Edat: 35
Grup edat: 26-40
Comportament: 3
Missatge: Cistella abandonat fa menys de 24h
Factor codi: 0.75
Factor edat: 1.0
Risc final: 0.75

In [ ]:
# Resultado final para Marketing

main_marketing()

PREGUNTA 1:   Clients per campanya de retargeting
--- Cliente 1 ---
Nom: Laura Serra
Edat: 23
Grup edat: 18-25
Comportament: 4
Missatge: Cistella abandonat fa més de 24h
Factor codi: 0.9
Factor edat: 1.2
Risc final: 1.08

--- Cliente 10 ---
Nom: Núria Costa
Edat: 33
Grup edat: 26-40
Comportament: 4
Missatge: Cistella abandonat fa més de 24h
Factor codi: 0.9
Factor edat: 1.0
Risc final: 0.9

--- Cliente 5 ---
Nom: Mónica Pérez
Edat: 47
Grup edat: 41-60
Comportament: 4
Missatge: Cistella abandonat fa més de 24h
Factor codi: 0.9
Factor edat: 0.85
Risc final: 0.77

--- Cliente 2 ---
Nom: Marc Vidal
Edat: 35
Grup edat: 26-40
Comportament: 3
Missatge: Cistella abandonat fa menys de 24h
Factor codi: 0.75
Factor edat: 1.0
Risc final: 0.75

--- Cliente 4 ---
Nom: Joan Riera
Edat: 19
Grup edat: 18-25
Comportament: 2
Missatge: Arriba al checkout però no paga
Factor codi: 0.5
Factor edat: 1.2
Risc final: 0.6

--- Cliente 7 ---
Nom: Pilar Sánchez
Edat: 61
Grup edat: 60+
Comportament: 3
Missatge: Cistella abandonat fa menys de 24h
Factor codi: 0.75
Factor edat: 0.7
Risc final: 0.52

--- Cliente 3 ---
Nom: Ana López
Edat: 29
Grup edat: 26-40
Comportament: 2
Missatge: Arriba al checkout però no paga
Factor codi: 0.5
Factor edat: 1.0
Risc final: 0.5

--- Cliente 9 ---
Nom: Diego Romero
Edat: 24
Grup edat: 18-25
Comportament: 1
Missatge: Afegeix productes però no arriba al checkout
Factor codi: 0.25
Factor edat: 1.2
Risc final: 0.3

--- Cliente 6 ---
Nom: Luis García
Edat: 52
Grup edat: 41-60
Comportament: 1
Missatge: Afegeix productes però no arriba al checkout
Factor codi: 0.25
Factor edat: 0.85
Risc final: 0.21

--- Cliente 8 ---
Nom: Eva Martín
Edat: 38
Grup edat: 26-40
Comportament: 0
Missatge: Navega però no afegeix productes
Factor codi: 0.1
Factor edat: 1.0
Risc final: 0.1

PREGUNTA 2:   Clients amb el mateix comportament

--- Comportament 4 ---
--- Cliente 1 ---
Nom: Laura Serra
Edat: 23
Grup edat: 18-25
Comportament: 4
Missatge: Cistella abandonat fa més de 24h
Factor codi: 0.9
Factor edat: 1.2
Risc final: 1.08

--- Cliente 5 ---
Nom: Mónica Pérez
Edat: 47
Grup edat: 41-60
Comportament: 4
Missatge: Cistella abandonat fa més de 24h
Factor codi: 0.9
Factor edat: 0.85
Risc final: 0.77

--- Cliente 10 ---
Nom: Núria Costa
Edat: 33
Grup edat: 26-40
Comportament: 4
Missatge: Cistella abandonat fa més de 24h
Factor codi: 0.9
Factor edat: 1.0
Risc final: 0.9


--- Comportament 3 ---
--- Cliente 2 ---
Nom: Marc Vidal
Edat: 35
Grup edat: 26-40
Comportament: 3
Missatge: Cistella abandonat fa menys de 24h
Factor codi: 0.75
Factor edat: 1.0
Risc final: 0.75

--- Cliente 7 ---
Nom: Pilar Sánchez
Edat: 61
Grup edat: 60+
Comportament: 3
Missatge: Cistella abandonat fa menys de 24h
Factor codi: 0.75
Factor edat: 0.7
Risc final: 0.52


--- Comportament 2 ---
--- Cliente 3 ---
Nom: Ana López
Edat: 29
Grup edat: 26-40
Comportament: 2
Missatge: Arriba al checkout però no paga
Factor codi: 0.5
Factor edat: 1.0
Risc final: 0.5

--- Cliente 4 ---
Nom: Joan Riera
Edat: 19
Grup edat: 18-25
Comportament: 2
Missatge: Arriba al checkout però no paga
Factor codi: 0.5
Factor edat: 1.2
Risc final: 0.6


--- Comportament 1 ---
--- Cliente 6 ---
Nom: Luis García
Edat: 52
Grup edat: 41-60
Comportament: 1
Missatge: Afegeix productes però no arriba al checkout
Factor codi: 0.25
Factor edat: 0.85
Risc final: 0.21

--- Cliente 9 ---
Nom: Diego Romero
Edat: 24
Grup edat: 18-25
Comportament: 1
Missatge: Afegeix productes però no arriba al checkout
Factor codi: 0.25
Factor edat: 1.2
Risc final: 0.3


--- Comportament 0 ---
--- Cliente 8 ---
Nom: Eva Martín
Edat: 38
Grup edat: 26-40
Comportament: 0
Missatge: Navega però no afegeix productes
Factor codi: 0.1
Factor edat: 1.0
Risc final: 0.1

PREGUNTA 3:   Clients amb poc interès
--- Cliente 8 ---
Nom: Eva Martín
Edat: 38
Grup edat: 26-40
Comportament: 0
Missatge: Navega però no afegeix productes
Factor codi: 0.1
Factor edat: 1.0
Risc final: 0.1

PREGUNTA 4:   Clients més rendibles de recuperar
--- Cliente 2 ---
Nom: Marc Vidal
Edat: 35
Grup edat: 26-40
Comportament: 3
Missatge: Cistella abandonat fa menys de 24h
Factor codi: 0.75
Factor edat: 1.0
Risc final: 0.75

### 📝 Notas sobre el ejercicio

*   Se utilizó `pprint` para dar mejor visibilidad a la prueba de uso aunque no se utilizó dentro la ejecución del resultado final.
*   Se resolvieron las preguntas por separado ya que cada una requería un análisis distinto, por ejemplo ordenar por `risc_final`, agrupar por comportamiento o filtrar segmentos, así que no todas podían mostrarse de la misma forma.
*   En la última pregunta se decidió qué segmentos considerar como más recuperables, ya que el ejercicio no lo especificaba de forma exacta.

# Nivell 2

## **Exercici 1**: Gestió de risc i priorització de pacients

### 🚩 Problema planteado

Treballes com a analista de dades en un centre mèdic especialitzat. Diversos pacients han enviat els seus símptomes a través d'un formulari online, però les dades arriben en un format desordenat i poc estructurat, i l'equip mèdic necessita que els organitzis per poder prioritzar l'ordre d'atenció segons la gravetat.

<br>

A continuació tens una llista amb informació real procedent del sistema:

`pacients = [ `
      
      "Maria|45|tos, Fiebre Alta, dolor_pecho",
      "Luis|33|dolor_cabeza,faTiga",
      "Sara|67|fiebre alta, dificultad RESPIRAR, tos",
      "Jordi|52|fatiga , tos",
      "Anna|29|fiebre alta,dolor_cabeza"
`]`

<br>

El departament mèdic també t'ha proporcionat el següent diccionari de nivells de risc per símptoma:

`nivells_risc = { `

    "fiebre_alta": 3,
    "dificultad_respirar": 5,
    "dolor_pecho": 4,
    "tos": 1,
    "fatiga": 1,
    "dolor_cabeza": 1
`}`

<br>

**🎯 Objectius**

L'objectiu és transformar aquestes dades en informació útil per als metges. A partir dels registres en brut, has de:

*   Convertir cada string en una estructura neta (diccionari o similar).
*   Separar i normalitzar la llista de símptomes:
      *   minúscules
      *   eliminar espais
      *   dividir correctament per comes
*   Assignar un risc a cada símptoma utilitzant el diccionari nivells_risc.
*   Calcular el risc total de cada pacient sumant els valors.
*   Ordenar els pacients de major a menor risc per determinar la prioritat d'atenció.

<br>

**⚠️ Important**

En aquest Nivell 2 ja no et proporcionem la llista de funcions que has de crear. Ets tu qui ha de plantejar quines funcions necessites i com modularitzar el procés.

Tot i així, es recomana que:

*   La funció principal orquestri tots els passos.
*   Cada subfunció faci una sola tasca concreta (neteja, conversió, càlcul, ordenació...).
*   La lògica estigui separada de manera neta i coherent.

<br>

**✅ Resultat esperat**

Un DataFrame o un diccionari amb:
*   nom
*   edat
*   símptomes normalitzats
*   risc_total

I un apartat final amb els pacients ordenats per prioritat (més risc → primer).

### 🧠 Análisis y planteamiento del ejercicio

👽 **Planteamiento básico**

1.   Limpiar y ordenar la información de los pacientes
2.   Limpiar y ordenar los síntomas de cada paciente
3.   Calcular el nivel de riesgo de cada paciente
4.   Incluir el dato de riesgo a cada paciente según sus sintomas ya estandarizados
5.   Crear una lista de pacientes (lista de diccionarios)
6.   Ordenar la lista de pacientes según su nivel de riesgo de mayor a menor
7.   Convertir la lista de diccionarios en un DataFrame
8.   Crear una función que orqueste todo el proceso y muestre el resultado final

💣**Algoritmo planteado**

1.   Recorrer la lista de pacientes y separar cada registro `separar_pacientes`
      *   nombre
      *   edad
      *   síntomas

2.   Estandarizar la ista de sintomas para que coincida con los niveles de riesgo `estandarizar_sintomas`
      *   dividir por comas
      *   eliminar espacios sobrantes
      *   pasar a minúsuclas
      *   sustituir espacios por `_`

3.   Calcular riesgo de cada paciente en base al registro de síntomas `calcular_riesgo_paciente`
4.   Crear un diccionario por cada paciente con toda su información `crear_paciente`
      *   nombre
      *   edad
      *   síntomas normalizados
      *   nivel de riesgo      
5.   Guardar cada diccionario en una lista de pacientes
6.   Ordenar el listado de pacientes de mayor a menor riesgo `ordenar_riesgo`
7.   Convertir el resultado final en un DataFrame para facilitar la visualización.
6.   Crear una función final de consulta de resultados `main_pacientes`

### 🧩 Desarrollo de funciones

⚡`separar_pacientes()`

1. Recibe string
2. Asigna claves especificas
3. Asigna valores a cada clave
4. Devuelve diccionario

In [ ]:
def separar_pacientes (string):

  claves = ["Nombre", "Edad", "Síntomas"]

  paciente = dict(zip(claves, string.split("|")))

  return paciente

In [ ]:
#Prueba de uso
paciente_1 = separar_pacientes ("Maria|45|tos, Fiebre Alta, dolor_pecho")

print(paciente_1)

{'Nombre': 'Maria', 'Edad': '45', 'Síntomas': 'tos, Fiebre Alta, dolor_pecho'}

⚡`estandarizar_sintomas()`

1. Recibe diccionario
2. Convierte todas las letras en minúsculas
3. Sustituye espacios por "under_score"
4. Devuelve el diccionario con la lista de síntomas limpia y estandarizada

In [ ]:
def estandarizar_sintomas(diccionario):

    sintomas = diccionario["Síntomas"].split(",")

    sintomas_limpios = []

    for sintoma in sintomas:
        sintoma = sintoma.strip()
        sintoma = sintoma.lower()
        sintoma = sintoma.replace(" ", "_")

        sintomas_limpios.append(sintoma)

    diccionario["Síntomas"] = sintomas_limpios

    return diccionario

In [ ]:
#Prueba de uso
paciente_2 = estandarizar_sintomas (paciente_1)

print(paciente_2)

{'Nombre': 'Maria', 'Edad': '45', 'Síntomas': ['tos', 'fiebre_alta', 'dolor_pecho']}

⚡`calcular_riesgo_paciente()`

1. Recibe diccionario.
2. Suma valores númericos si hay coincidencia de clave en el diccionario base.
3. Devuelve suma de las coincidencias.

In [ ]:
def calcular_riesgo_paciente (diccionario_paciente):

  nivells_risc = {
    "fiebre_alta": 3,
    "dificultad_respirar": 5,
    "dolor_pecho": 4,
    "tos": 1,
    "fatiga": 1,
    "dolor_cabeza": 1
  }

  clave_sintoma = diccionario_paciente["Síntomas"]
  riesgo_total = 0

  for sintoma in clave_sintoma:
    if sintoma in nivells_risc:
        riesgo_total = riesgo_total + nivells_risc[sintoma]

  return riesgo_total

In [ ]:
#Prueba de uso
prueba_maria = {
    'Nombre': 'Maria',
    'Edad': '45',
    'Síntomas': ['tos', 'fiebre_alta', 'dolor_pecho']
}

riesgo_maria = calcular_riesgo_paciente(prueba_maria)

print(riesgo_maria)

8

⚡`crear_paciente()`

1. Recibe diccionario.
2. Añade nueva clave y valor al diccionario.
3. Devuelve diccionario actualizado.

In [ ]:
def crear_paciente (diccionario_inicial):

  diccionario_inicial ["Riesgo"] = calcular_riesgo_paciente(diccionario_inicial)

  return diccionario_inicial

In [ ]:
#Prueba de uso
paciente_maria = {
    'Nombre': 'Maria',
    'Edad': '45',
    'Síntomas': ['tos', 'fiebre_alta', 'dolor_pecho']
}

crear_maria = crear_paciente (paciente_maria)

print(crear_maria)

{'Nombre': 'Maria', 'Edad': '45', 'Síntomas': ['tos', 'fiebre_alta', 'dolor_pecho'], 'Riesgo': 8}

⚡`ordenar_riesgo()`

1. Recibe lista de diccionarios.
2. Ordena la lista por el valor de una clave específica de mayor a menor.
3. Devuelve lista de diccionarios ordenada.

In [ ]:
def ordenar_riesgo(lista_pacientes):

    return sorted(
        lista_pacientes,
        key=lambda x: x["Riesgo"],
        reverse=True
    )

In [ ]:
#Prueba de uso
prueba_pacientes = [
    {"Nombre": "Maria", "Riesgo": 8},
    {"Nombre": "Luis", "Riesgo": 2},
    {"Nombre": "Sara", "Riesgo": 9}
]

resultado = ordenar_riesgo(prueba_pacientes)

print(resultado)

[{'Nombre': 'Sara', 'Riesgo': 9}, {'Nombre': 'Maria', 'Riesgo': 8}, {'Nombre': 'Luis', 'Riesgo': 2}]

⚡`main_pacientes()`

1. Recibe una lista sin formato.
2. Aplica las funciones creadas.
3. Devuelve un DataFrame con los pacientes ordenados por nivel de riesgo.

In [ ]:
import pandas as pd

In [ ]:
def main_pacientes(lista_inicial):

    lista_pacientes = []

    for paciente in lista_inicial:

        paciente_separado = separar_pacientes(paciente)
        paciente_limpio = estandarizar_sintomas(paciente_separado)
        paciente_final = crear_paciente(paciente_limpio)

        lista_pacientes.append(paciente_final)

    pacientes_ordenados = ordenar_riesgo(lista_pacientes)

    return pd.DataFrame(pacientes_ordenados)

In [ ]:
#Prueba de uso
pacientes_prueba = [
    "Carlos|40|Tos, dolor_pecho",
    "Lucia|25|fatiga, Dolor Cabeza",
    "Pedro|70|Fiebre Alta, dificultad RESPIRAR"
]

prueba_main = main_pacientes(pacientes_prueba)

print(prueba_main)

   Nombre Edad                            Síntomas  Riesgo
0   Pedro   70  [fiebre_alta, dificultad_respirar]       8
1  Carlos   40                  [tos, dolor_pecho]       5
2   Lucia   25              [fatiga, dolor_cabeza]       2

### 🏆 Resultado final

In [ ]:
# Ejecución de main_pacientes con datos reales del ejercicio

pacients = [

  "Maria|45|tos, Fiebre Alta, dolor_pecho",
  "Luis|33|dolor_cabeza,faTiga",
  "Sara|67|fiebre alta, dificultad RESPIRAR, tos",
  "Jordi|52|fatiga , tos",
  "Anna|29|fiebre alta,dolor_cabeza"
]

resultado_final = main_pacientes(pacients)

print(resultado_final)

  Nombre Edad                                 Síntomas  Riesgo
0   Sara   67  [fiebre_alta, dificultad_respirar, tos]       9
1  Maria   45          [tos, fiebre_alta, dolor_pecho]       8
2   Anna   29              [fiebre_alta, dolor_cabeza]       4
3   Luis   33                   [dolor_cabeza, fatiga]       2
4  Jordi   52                            [fatiga, tos]       2

### 📝 Notas sobre el ejercicio

*   Se prestó especial atención a la asignación de nombres claros y diferenciados para cada función, ya que algunas realizan tareas similares dentro del flujo pero con responsabilidades distintas. Esto facilita la lectura, el mantenimiento y la depuración del código.
*   El resultado final se presenta en un DataFrame para mejorar la visualización de la información.
*   Durante las pruebas fue necesario revisar el flujo entre funciones para asegurar que cada una recibiera y devolviera el tipo de dato esperado (`string`, `dict`, `list`). Esto ayudó a detectar errores de integración entre funciones que, por separado, funcionaban correctamente.

## **Exercici 2**: Classificació de clients de segurs

### 🚩 Problema planteado

Treballes com a analista de dades en una companyia asseguradora. L'empresa vol calcular el risc dels clients, el preu estimat de la pòlissa i la probabilitat de frau, utilitzant un codi de comportament que ha estat generat per un model intern.

<br>

Tens la següent llista de clients:

`clients = [ `
      
      {"nom": "Ana", "edat": 42, "codi": 0},
      {"nom": "Carlos", "edat": 30, "codi": 2},
      {"nom": "Isabel", "edat": 55, "codi": 3},
      {"nom": "Jorge", "edat": 40, "codi": 1},
      {"nom": "Marta", "edat": 28, "codi": 0}
`]`

<br>

I aquest diccionari amb les categories del sistema:

`nivells_seguro = { `

    0: {"categoria": "Baix risc", "preu_base": 120, "fraude": 0.01},
    1: {"categoria": "Risc mitjà", "preu_base": 200, "fraude": 0.05},
    2: {"categoria": "Risc alt", "preu_base": 350, "fraude": 0.15},
    3: {"categoria": "Risc crític", "preu_base": 500, "fraude": 0.30}
`}`

<br>

El preu final s'ha de calcular amb la fórmula:

`preu_final = preu_base * (1 + edat/100)`

<br>

**🎯 Objectius**

*   Classificar cada client utilitzant nivells_seguro (sense if/elif).
*   Afegir:
    *   La categoria
    *   El preu base
    *   La probabilitat de frau
*   Calcular el preu final de la pòlissa amb la fórmula donada.
*   Crear un DataFrame o diccionari amb la informació final.
*   Ordenar els clients:
    *   Per probabilitat de frau (descendent).
    *   Per preu final.

<br>

**⚠️ Important**

Igual que a l'Exercici 1, en aquest nivell ets tu qui ha de definir les funcions necessàries. Es recomana mantenir el codi modular, on:

*   Cada funció resol un pas del procés.
*   La funció principal delega totes les tasques.

<br>

**✅ Resultat esperat**

Un DataFrame o un diccionari amb:
*   Nom
*   Edat
*   Categoria
*   Preu_base
*   Preu_final
*   Probabilitat_frau
*   Un apartat d'anàlisi on s'indiqui:
    *   Quin client té més probabilitat de frau
    *   Quin té el preu final més alt
    *   Qui seria prioritari de revisar manualment

### 🧠 Análisis y planteamiento del ejercicio

👽 **Planteamiento básico**

1.   Asignar a cada cliente los niveles de seguro según su código
2.   Calcular el precio final para cada cliente
3.   Actualizar la lista de clientes con todos los datos
4.   Ordenar la lista de clientes por parámetros solicitados
5.   Convertir la lista de diccionarios en un DataFrame
6.   Analizar resultados para responder preguntas específicas
7.   Crear una función que orqueste todo el proceso y muestre el resultado final

💣**Algoritmo planteado**

1.   Recorrer la lista de clientes y asignar las claves adicionales según su código `add_nivells`
      *   categoria
      *   preu_base
      *   fraude

2.   Calcular precio de poliza `calcular_preu`
3.   Añadir el precio calculado a cada cliente según sus datos `add_preu`
4.   Ordenar listado de clientes por parámetros `ordenar_clients`
      *   fraude descendente
      *   preu poliza
5.   Convertir el resultado final en un DataFrame para facilitar la visualización.
6.   Analizar datos para responder preguntas `analitzar_clients`
      *   `client_major_fraude`
      *   `client_major_preu`
      *   `client_revisio_manual`
6.   Crear una función final `main_clients`

### 🧩 Desarrollo de funciones

⚡`add_nivells()`

1. Recibe un diccionario.
2. Compara con diccionario interno.
3. Asigna claves especificas.
4. Asigna valores a cada clave.
5. Devuelve diccionario.

In [ ]:
def add_nivells (diccionario_inicial):

  nivells_seguro = {

    0: {"categoria": "Baix risc", "preu_base": 120, "fraude": 0.01},
    1: {"categoria": "Risc mitjà", "preu_base": 200, "fraude": 0.05},
    2: {"categoria": "Risc alt", "preu_base": 350, "fraude": 0.15},
    3: {"categoria": "Risc crític", "preu_base": 500, "fraude": 0.30}
  }

  nivell_actual = diccionario_inicial["codi"]

  diccionario_inicial.update(nivells_seguro[nivell_actual])

  return diccionario_inicial

In [ ]:
#Prueba de uso
cliente_prueba = {
    "nom": "Lucía",
    "edat": 37,
    "codi": 2
}

prueba_uso_01 = add_nivells(cliente_prueba)
print(prueba_uso_01)

{'nom': 'Lucía', 'edat': 37, 'codi': 2, 'categoria': 'Risc alt', 'preu_base': 350, 'fraude': 0.15}

⚡`calcular_preu()`

1. Recibe diccionario
2. Aplica fórmula matemática si hay coincidencia de claves en el diccionario base
3. Devuelve el resultado de la fórmula

In [ ]:
def calcular_preu (diccionario_cliente):

  clave_preu = diccionario_cliente["preu_base"]
  clave_edat = diccionario_cliente["edat"]

  preu_poliza = clave_preu * (1 + clave_edat / 100)

  return round(preu_poliza, 2)

In [ ]:
#Prueba de uso
prueba_02 = {
    "nom": "Lucía",
    "edat": 37,
    "codi": 2,
    "categoria": "Risc alt",
    "preu_base": 350,
    "fraude": 0.15
}

prueba_uso_02 = calcular_preu(prueba_02)
print(prueba_uso_02)

479.5

⚡`add_preu()`

1. Recibe diccionario.
2. Añade nueva clave y valor al diccionario.
3. Devuelve diccionario actualizado.

In [ ]:
def add_preu (diccionario_incompleto):

  diccionario_incompleto ["preu_final"] = calcular_preu(diccionario_incompleto)

  return diccionario_incompleto

In [ ]:
#Prueba de uso
cliente_x = {
    "nom": "Marc",
    "edat": 45,
    "codi": 1,
    "categoria": "Risc mitjà",
    "preu_base": 200,
    "fraude": 0.05
}

prueba_uso_03 = add_preu (cliente_x)

print(prueba_uso_03)

{'nom': 'Marc', 'edat': 45, 'codi': 1, 'categoria': 'Risc mitjà', 'preu_base': 200, 'fraude': 0.05, 'preu_final': 290.0}

⚡`ordenar_clients()`

1. Recibe lista de diccionarios
2. Ordena por fraude descendente
3. En caso de empate, ordena por preu_final ascendente
4. Devuelve un DataFrame con los clientes ordenados

In [ ]:
def ordenar_clients(lista_clients):

    clients_ordenats = sorted(
        lista_clients,
        key=lambda x: (-x["fraude"], x["preu_final"])
    )

    df_clients = pd.DataFrame(clients_ordenats)

    return df_clients

In [ ]:
#Prueba de uso
clients_04 = [
    {"nom": "Laura", "fraude": 0.15, "preu_final": 420.0},
    {"nom": "Pau", "fraude": 0.30, "preu_final": 610.0},
    {"nom": "Mireia", "fraude": 0.30, "preu_final": 550.0},
    {"nom": "Joan", "fraude": 0.05, "preu_final": 300.0}
]

prueba_uso_04 = ordenar_clients (clients_04)

print(prueba_uso_04)

      nom  fraude  preu_final
0  Mireia    0.30       550.0
1     Pau    0.30       610.0
2   Laura    0.15       420.0
3    Joan    0.05       300.0

⚡`analitzar_clients()`

1. Recibe un DataFrame.
2. Ejecuta `client_major_fraude()`.
      
    2.1 Recibe un DataFrame.

    2.2 Busca el valor máximo en fraude.
    
    2.3 Devuelve la fila del cliente.
3. Ejecuta `client_major_preu()`.
      
    3.1 Recibe un DataFrame.

    3.2 Busca el valor máximo en preu_final.
    
    3.3 Devuelve la fila del cliente.
4. Ejecuta `client_revisio_manual()`.

    4.1 Recibe un DataFrame.

    4.2 Busca los clientes con "Risc crític" o "Risc alt".
    
    4.3 Devuelve el DataFrame de clientes seleccionados.

5. Devuelve los resultados del análisis.

In [ ]:
def client_major_fraude(df_clients):

    index_major_fraude = df_clients["fraude"].idxmax()
    major_fraude = df_clients.loc[index_major_fraude]

    return major_fraude

In [ ]:
def client_major_preu(df_clients):

    index_major_preu = df_clients["preu_final"].idxmax()
    major_preu = df_clients.loc[index_major_preu]

    return major_preu

In [ ]:
def client_revisio_manual(df_clients):

    revisio_manual = df_clients[
        df_clients["categoria"].isin(["Risc crític", "Risc alt"])
    ]

    return revisio_manual

In [ ]:
def analitzar_clients(df_clients):

    major_fraude = client_major_fraude(df_clients)
    major_preu = client_major_preu(df_clients)
    revisio_manual = client_revisio_manual(df_clients)

    print("El client amb major probabilitat de frau és:")
    print(major_fraude)

    print("\nEl client amb el preu final més alt és:")
    print(major_preu)

    print("\nClients prioritaris per revisió manual:")
    print(revisio_manual)

    return major_fraude, major_preu, revisio_manual

In [ ]:
#Prueba de uso
import pandas as pd

df_prueba = pd.DataFrame([
    {
        "nom": "Laura",
        "edat": 35,
        "categoria": "Risc alt",
        "preu_final": 470.0,
        "fraude": 0.15
    },
    {
        "nom": "Pau",
        "edat": 50,
        "categoria": "Risc crític",
        "preu_final": 750.0,
        "fraude": 0.30
    },
    {
        "nom": "Mireia",
        "edat": 42,
        "categoria": "Risc crític",
        "preu_final": 710.0,
        "fraude": 0.30
    },
    {
        "nom": "Joan",
        "edat": 28,
        "categoria": "Baix risc",
        "preu_final": 153.6,
        "fraude": 0.01
    }
])

prueba_uso_05 = analitzar_clients(df_prueba)

El client amb major probabilitat de frau és:
nom                   Pau
edat                   50
categoria     Risc crític
preu_final          750.0
fraude                0.3
Name: 1, dtype: object

El client amb el preu final més alt és:
nom                   Pau
edat                   50
categoria     Risc crític
preu_final          750.0
fraude                0.3
Name: 1, dtype: object

Clients prioritaris per revisió manual:
      nom  edat    categoria  preu_final  fraude
0   Laura    35     Risc alt       470.0    0.15
1     Pau    50  Risc crític       750.0    0.30
2  Mireia    42  Risc crític       710.0    0.30

⚡`main_clients()`

1. Recibe una lista de diccionarios
2. Aplica las funciones creadas
3. Devuelve el DataFrame de clientes ordenados y los resultados del análisis

In [ ]:
def main_clients(lista_inicial_clientes):

    lista_clientes_procesados = []

    for cliente in lista_inicial_clientes:

        niveles = add_nivells(cliente)
        preu_final = add_preu(niveles)

        lista_clientes_procesados.append(preu_final)

    clientes_ordenados = ordenar_clients(lista_clientes_procesados)

    print("Clients ordenats:")
    display(clientes_ordenados)

    clientes_analizados = analitzar_clients(clientes_ordenados)

    return clientes_ordenados, clientes_analizados

In [ ]:
#Prueba de uso
clientes_prueba_06 = [
    {"nom": "Ana", "edat": 42, "codi": 0},
    {"nom": "Carlos", "edat": 30, "codi": 2},
    {"nom": "Isabel", "edat": 55, "codi": 3}
]

prueba_uso_06 = main_clients(clientes_prueba_06)

Clients ordenats:

      nom  edat  codi    categoria  preu_base  fraude  preu_final
0  Isabel    55     3  Risc crític        500    0.30       775.0
1  Carlos    30     2     Risc alt        350    0.15       455.0
2     Ana    42     0    Baix risc        120    0.01       170.4

El client amb major probabilitat de frau és:
nom                Isabel
edat                   55
codi                    3
categoria     Risc crític
preu_base             500
fraude                0.3
preu_final          775.0
Name: 0, dtype: object

El client amb el preu final més alt és:
nom                Isabel
edat                   55
codi                    3
categoria     Risc crític
preu_base             500
fraude                0.3
preu_final          775.0
Name: 0, dtype: object

Clients prioritaris per revisió manual:
      nom  edat  codi    categoria  preu_base  fraude  preu_final
0  Isabel    55     3  Risc crític        500    0.30       775.0
1  Carlos    30     2     Risc alt        350    0.15       455.0

### 🏆 Resultado final

In [ ]:
# Ejecución de main_clients con datos reales del ejercicio

clients = [

  {"nom": "Ana", "edat": 42, "codi": 0},
  {"nom": "Carlos", "edat": 30, "codi": 2},
  {"nom": "Isabel", "edat": 55, "codi": 3},
  {"nom": "Jorge", "edat": 40, "codi": 1},
  {"nom": "Marta", "edat": 28, "codi": 0}
]

datos_finales = main_clients(clients)

Clients ordenats:

      nom  edat  codi    categoria  preu_base  fraude  preu_final
0  Isabel    55     3  Risc crític        500    0.30       775.0
1  Carlos    30     2     Risc alt        350    0.15       455.0
2   Jorge    40     1   Risc mitjà        200    0.05       280.0
3   Marta    28     0    Baix risc        120    0.01       153.6
4     Ana    42     0    Baix risc        120    0.01       170.4

El client amb major probabilitat de frau és:
nom                Isabel
edat                   55
codi                    3
categoria     Risc crític
preu_base             500
fraude                0.3
preu_final          775.0
Name: 0, dtype: object

El client amb el preu final més alt és:
nom                Isabel
edat                   55
codi                    3
categoria     Risc crític
preu_base             500
fraude                0.3
preu_final          775.0
Name: 0, dtype: object

Clients prioritaris per revisió manual:
      nom  edat  codi    categoria  preu_base  fraude  preu_final
0  Isabel    55     3  Risc crític        500    0.30       775.0
1  Carlos    30     2     Risc alt        350    0.15       455.0

### 📝 Notas sobre el ejercicio

*   En el resultado final se decidió mostrar tanto las respuestas del análisis y también el DataFrame completo con los clientes ordenados para facilitar la lectura.
*   Para la ordenación, no especifica el sentido del criterio `preu_final`, por lo que se decidió ordenarlo de forma ascendente en caso de empate.
*   El criterio de “revisión manual” tampoco está definido por lo que se decidió considerar prioritarios a los clientes clasificados como `Risc alt` y `Risc crític`.
*   Las funciones de análisis trabajan sobre un DataFrame, mientras que las funciones de transformación inicial trabajan sobre diccionarios individuales. Esto permitió separar el procesamiento de cada cliente del análisis global de los resultados.
*   Para evitar duplicados se descartó añadir un `print()` en el apartado de "Resultado final" ya que `analitzar_clients()` ya se encarga de mostrar los datos.

# Nivell 3

## **Exercici 1**: Generador de contrasenyes segures

### 🚩 Problema planteado

Ets analista de dades dins el departament de Ciberseguretat d'una empresa tecnològica. S'ha detectat que la majoria de treballadors continuen utilitzant contrasenyes molt dèbils com “Asdf1234”, dates d'aniversari o combinacions fàcils d'endevinar. Per aquest motiu, el responsable del departament t'ha demanat desenvolupar un generador de contrasenyes segures, totalment parametritzable i modular.

<br>

**📝 Requisits del generador**

Has de crear una funció principal i totes les subfuncions necessàries per:

*   Generar contrasenyes de longitud variable.
*   Decidir si han d'incloure:
    *   Majúscules
    *   Minúscules
    *   Números
    *   Signes especials
*   Assegurar-te que com a mínim apareix un caràcter de cada tipus seleccionat.
*   Aleatoritzar completament la contrasenya.
*   Retornar la contrasenya generada.

<br>

**📍 Nota important**

Explora el funcionament del mòdul random de la llibreria icona enllaçnumpy

La funció principal del generador ha de tenir valors per defecte, exactament els següents:

*   majuscules=True
*   minuscules=True
*   numeros=True
*   signes=False

Aquests paràmetres són obligatoris i formen part del disseny del sistema.

<br>

**👁️ Exemple d'ús esperat**

`crear_contrasenya(12,majuscules=True, minuscules=True, numeros=True, signes=True)`

Output possible:

`WS6MwfRD:%B3`

### 🧠 Análisis y planteamiento del ejercicio

👽 **Planteamiento básico**

1.   Definir parámetros básicos para la creación de contraseñas
2.   Seleccionar los caracteres mínimos imprescindibles
3.   Calcular los caracteres restantes para la longitud establecida
4.   Completar la contraseña con caracteres aleatorios
5.   Reordenar la contraseña final
6.   Convertir la contraseña final en texto
7.   Crear una función que orqueste todo el proceso y devuelva una contraseña segura

💣**Algoritmo planteado**

1.   Recibir longitud y parámetros de configuración `pw_must`
2.   Seleccionar los caracteres definidos por el usuario con *string* `pw_elements`
3.   Calcular los caracteres restantes para llegar al length definido `pw_length`
4.   Completar la contraseña con elementos de forma aleatoria `pw_complete`
5.   Reordenar todos los caracteres de la contraseña y convierte la lista en texto `pw_clean`
6.   Crear una función final que coordine todo el proceso `main_password`

### 🧩 Desarrollo de funciones

⚡`pw_must()`

1. Recibe la longitud mínima que deberá tener la contraseña
2. Pregunta al usuario la longitud de su contraseña
3. Envía mensaje de error si la longitud seleccionada es inferior a la mínima establecida.
4. Pregunta al usuario que tipo de caracteres quiere incluir (True/False).
5. Devuelve length y elementos mínimos de creación.

In [ ]:
def pw_must (min_length):

  length = int(input(f"¿Cuántos caracteres quieres para tu contraseña (minimo {min_length})? "))

  while length < min_length:
      print(f"Recuerda que la contraseña debe tener un mínimo de {min_length} caracteres.")
      length = int(input("¿Cuántos caracteres quieres para tu contraseña? "))

  mayuscula = input("¿Quieres mayúsculas? (Si/No) ").strip().lower() in ("si", "sí")
  minuscula = input("¿Quieres minúsculas? (Si/No) ").strip().lower() in ("si", "sí")
  numero = input("¿Quieres números? (Si/No) ").strip().lower() in ("si", "sí")
  simbolo = input("¿Quieres símbolos? (Si/No) ").strip().lower() in ("si", "sí")

  return length, mayuscula, minuscula, numero, simbolo

In [ ]:
#Prueba de uso
prueba_pw_must = pw_must(10)

print(prueba_pw_must)

¿Cuántos caracteres quieres para tu contraseña (minimo 10)? 15
¿Quieres mayúsculas? (Si/No) si
¿Quieres minúsculas? (Si/No) si
¿Quieres números? (Si/No) no
¿Quieres símbolos? (Si/No) si
(15, True, True, False, True)

⚡`pw_elements()`

1. Recibe elementos a buscar (True/False)
2. Define un caracter aleatorio por cada elemento
3. Añade cada elemento en formato `string` de Python a un lista
3. Devuelve  lista de caracteres minimos

In [ ]:
import string
import numpy as np

In [ ]:
def pw_elements(mayuscula, minuscula, numero, simbolo):

    p_list = []
    azar = np.random.default_rng()

    if mayuscula:
        mayusculas = string.ascii_uppercase
        e_mayuscula = azar.choice(list(mayusculas))
        p_list.append(str(e_mayuscula))

    if minuscula:
        minusculas = string.ascii_lowercase
        e_minuscula = azar.choice(list(minusculas))
        p_list.append(str(e_minuscula))

    if numero:
        numeros = string.digits
        e_numero = azar.choice(list(numeros))
        p_list.append(str(e_numero))

    if simbolo:
        simbolos = string.punctuation
        e_simbolo = azar.choice(list(simbolos))
        p_list.append(str(e_simbolo))

    return p_list

In [ ]:
#Prueba de uso

prueba_pw_elements = pw_elements(True, True, False, True)

print(prueba_pw_elements)

['E', 'n', '\\']

⚡`pw_length()`

1. Recibe la longitud establecida en `length` y el número de elementos mínimos establecidos (True/False)
2. Calcula la lista de caracteres mínimos generada por `pw_elements()`
3. Devuelve un resultado númerico

In [ ]:
def pw_length (length, pw_basic):

  pw_faltantes = length - len(pw_basic)

  return pw_faltantes

In [ ]:
#Prueba de uso
pw_prueba = ["I", "m", "9"]

prueba_pw_length = pw_length(10, pw_prueba)

print(prueba_pw_length)

7

⚡`pw_complete()`

1. Recibe los resultados de las funciones anteriores (lista de caracteres basicos, numero de caracteres faltantes y valores True/False)
2. Crea un `pool` con todos los caracteres permitidos según los valores True/False.
3. Selecciona aleatoriamente tantos caracteres del `pool` como se necesite y los añade a la lista original
4. Devuelve una lista con la longitud total establecida en `length`

In [ ]:
def pw_complete(pw_basic, pw_faltantes, mayuscula, minuscula, numero, simbolo):

    pool = ""

    if mayuscula:
        pool += string.ascii_uppercase

    if minuscula:
        pool += string.ascii_lowercase

    if numero:
        pool += string.digits

    if simbolo:
        pool += string.punctuation

    azar = np.random.default_rng()

    extras = azar.choice(
        list(pool),
        size=pw_faltantes
    )

    pw_basic.extend(extras.tolist())

    return pw_basic

In [ ]:
#Prueba de uso
pw_1 = ["I", "m", "9"]
pw_2 = 8


prueba_pw_complete = pw_complete(pw_1, pw_2, True, True, False, True)

print(prueba_pw_complete)

['I', 'm', '9', 'b', 'g', 'A', "'", 'd', '(', 't', 'h']

⚡`pw_clean()`

1. Recibe una lista con distintos elementos
2. Reordena de forma aleatoria los elementos de la lista
3. Convierte la lista en un `string`
3. Devuelve un `string`

In [ ]:
def pw_clean (pw_complete_list):

  azar = np.random.default_rng()

  azar.shuffle(pw_complete_list)

  return "".join(pw_complete_list)

In [ ]:
#Prueba de uso
pw_complete_01 = ['I', 'm', '9', '<', 'y', 'z', '"', 'I', 'f', '$', '$']

prueba_pw_clean = pw_clean(pw_complete_01)

print(prueba_pw_clean)

"y9$<$zmIIf

⚡`main_password()`

1. Recibe de forma externa los resultados obtenidos por `pw_must`
2. Crea una lista de caractares basicos con `pw_elements`
3. Calcula los caracteres faltantes con `pw_length`
4. Completa la lista de caracteres con `pw_complete`
5. Reordena y convierte la lista en `string` con `pw_clean`
6. Devuelve la contraseña final

In [ ]:
def main_password(
    length,
    mayuscula=True,
    minuscula=True,
    numero=True,
    simbolo=False):

    if not any((mayuscula, minuscula, numero, simbolo)):
        raise ValueError(
            "Debe seleccionarse al menos un tipo de carácter.")


    pw_basic = pw_elements(
        mayuscula,
        minuscula,
        numero,
        simbolo
    )

    pw_faltantes = pw_length(
        length,
        pw_basic
    )

    pw_list = pw_complete(
        pw_basic,
        pw_faltantes,
        mayuscula,
        minuscula,
        numero,
        simbolo
    )

    password = pw_clean(pw_list)

    print(password)

    return password

In [ ]:
#Prueba de uso

password_final = main_password (15, True, False, True, True)

S02H&[;&*_"]6VC

### 🏆 Resultado final

In [ ]:
#Solicitud externa de variables para main_password

datos_rrhh = pw_must(12)
print(datos_rrhh)

¿Cuántos caracteres quieres para tu contraseña (minimo 12)? 10
Recuerda que la contraseña debe tener un mínimo de 12 caracteres.
¿Cuántos caracteres quieres para tu contraseña? 12
¿Quieres mayúsculas? (Si/No) si
¿Quieres minúsculas? (Si/No) NO
¿Quieres números? (Si/No) si
¿Quieres símbolos? (Si/No) Si
(12, True, False, True, True)

In [ ]:
#Activación de main_password con los datos obtenidos

password_rrhh = main_password(12, True, False, True, True)

M@+G:N""6RX-

### 📝 Notas sobre el ejercicio

1. Se evaluó la posibilidad de utilizar únicamente parámetros en la función principal, pero como el enunciado no dejaba del todo claro cómo mantener el generador “parametritzable i modular”, se decidió incorporar `pw_must()` como función externa para recoger la longitud y los tipos de caracteres de la contraseña.
2. Por la misma razón, `main_password()` mantiene los parámetros exigidos por el enunciado y puede funcionar de forma independiente, sin necesidad de utilizar `pw_must()`.
3. Aunque se buscó que cada función tuviera una tarea concreta, se decidió que `pw_clean()` realizara dos acciones: reordenar los caracteres y convertir la lista final en string, ya que ambas tareas son simples y forman parte del mismo paso final.
4. Si se utiliza `pw_must()`, otra forma de pasar sus resultados a `main_password()` es utilizando `*`, que permite desempaquetar directamente los valores devueltos por la función.
5. En `pw_elements()` se mantuvo una estructura con varios `if` para gestionar cada tipo de carácter por separado. Aunque podría haberse simplificado con un bucle y una estructura común, se decidió mantener esta versión porque resulta más clara y fácil de seguir.
6. Se incluyó una validación en `main_password()` para comprobar que se haya seleccionado al menos un tipo de carácter y evitar errores en la generación de la contraseña.

## **Exercici 2**: Processament automàtic de dades esportives

### 🚩 Problema planteado

Ara formes part d'un equip d'analítica dins una organització esportiva que gestiona dades de la lliga catalana. La teva companya de feina vol automatitzar la lectura del seu arxiu històric de resultats i extreure les estadístiques més importants. T'ha demanat fer un petit sistema en Python que processi el fitxer 📄 "historic partits.txt"

<br>

**🎯 Objectius**

Mitjançant un codi modular, clar i documentat, el teu programa ha de calcular:

1. Quin equip és el més golejador.
2. Quin és el més golejat.
3. El nombre total de gols que ha fet cada equip.
4. La classificació final ordenada per punts on cada victòria suma 3 pts, cada empat 1 pts y cada derrota 0 pts.

<br>

En aquest nivell no es dona cap funció. Ets tu qui ha de dissenyar un flux complet. El codi ha de reflectir una bona organització interna.

<br>

**✅ Resultat esperat**

Un DataFrame o diccionari final semblant a:

<img src="https://drive.google.com/uc?export=view&id=1Ca9kkJBEYwhdbuT9psHE6xOUFzac1pMn" width="400">

*   imatge taula equips
*   A més del text:

    *   Equip més golejador: _______
    *   Equip més golejat: ________
    *   Classificació final:

            1. __
            2. __
...

### 🧠 Análisis y planteamiento del ejercicio

👽 **Planteamiento básico**

1. Limpiar y ordenar el archivo de datos .txt: dar nombre a las columnas, limpiar espacios y separar resultados.
2. Procesar cada partido para asignar resultados y puntuación.
3. Calcular estadísticas acumuladas por equipo.
4. Responder las preguntas específicas del ejercicio.
5. Mostrar los resultados y la clasificación global en un DataFrame.
6. Orquestar todo en una función general que agrupe todas las acciones.

💣**Algoritmo planteado**

1. Leer, limpiar y convertir el archivo en un DataFrame `cargar_partidos()`
2. Ordenar y separar resultados `crear_resultado()`
3. Recorrer los partidos y crear un diccionario de diccionarios con las estadísticas acumuladas de cada equipo `crear_estadisticas()`
4. Crear la clasificación de clubes `crear_clasificacion()`
5. Responder las preguntas específicas `obtener_destacados()`
6. Mostrar los resultados `mostrar_resultados()`
7. Orquestar todas las acciones `main_futbol()`

### 🧩 Desarrollo de funciones

In [ ]:
import pandas as pd

⚡`cargar_partidos()`

1. Recibe un archivo .txt
2. Asigna nombre a las columnas
3. Elimina espacios
5. Devuelve un DataFrame

In [ ]:
def cargar_partidos (archivo):

  data_partidos = pd.read_csv(archivo, sep="\t", header=None)

  data_partidos.columns = ["Local", "Resultado", "Visitante"]

  limpiar_espacios = ["Local", "Visitante", "Resultado"]

  data_partidos[limpiar_espacios] = (
      data_partidos[limpiar_espacios]
      .apply(lambda x: x.str.strip()))

  return data_partidos

In [ ]:
#Prueba de uso
p_cargar_partidos = cargar_partidos("/content/prueba_partidos.txt")

print(p_cargar_partidos)

        Local Resultado   Visitante
0     Manlleu       0-1  Granollers
1  Vilafranca       4-5    Terrassa
2        Olot       2-2   Girona FC

⚡`crear_resultado()`

1. Recibe un DataFrame
2. Separa el resultado global en `goles_local` y `goles_visitante`
3. Convierte goles a formato númerico
4. Devuelve un DataFrame actualizado

In [ ]:
def crear_resultado(data_partidos):

    columnas_goles = [
        "Goles Local",
        "Goles Visitante"]

    data_partidos[columnas_goles] = (
        data_partidos["Resultado"]
        .str.split("-", expand=True))

    data_partidos[columnas_goles] = (
        data_partidos[columnas_goles]
        .astype(int))

    return data_partidos

In [ ]:
#Prueba de uso
prueba_data = pd.DataFrame({
    "Local": ["Manlleu", "Vilafranca", "Olot"],
    "Resultado": ["0-1", "4-5", "2-2"],
    "Visitante": ["Granollers", "Terrassa", "Girona FC"]
})

p_crear_resultado = crear_resultado(prueba_data)
print(p_crear_resultado)

        Local Resultado   Visitante  Goles Local  Goles Visitante
0     Manlleu       0-1  Granollers            0                1
1  Vilafranca       4-5    Terrassa            4                5
2        Olot       2-2   Girona FC            2                2

⚡`crear_estadisticas()`

1. Recibe un DataFrame
2. Crea un diccionario vacío.
3. Recorre cada partido
4. Crea cada equipo si todavía no existe
5. Suma goles a favor y en contra
6. Suma partidos ganados, empatados y perdidos
7. Suma puntos
8. Devuelve un diccionario de diccionarios

In [ ]:
def crear_estadisticas(data_partidos):

    estadisticas = {}

    for _, partido in data_partidos.iterrows():

        local = partido["Local"]
        visitante = partido["Visitante"]
        goles_local = partido["Goles Local"]
        goles_visitante = partido["Goles Visitante"]

        if local not in estadisticas:
            estadisticas[local] = {
                "Goles Favor": 0,
                "Goles Contra": 0,
                "Ganados": 0,
                "Empatados": 0,
                "Perdidos": 0,
                "Puntos": 0}

        if visitante not in estadisticas:
            estadisticas[visitante] = {
                "Goles Favor": 0,
                "Goles Contra": 0,
                "Ganados": 0,
                "Empatados": 0,
                "Perdidos": 0,
                "Puntos": 0}

        estadisticas[local]["Goles Favor"] += goles_local
        estadisticas[local]["Goles Contra"] += goles_visitante

        estadisticas[visitante]["Goles Favor"] += goles_visitante
        estadisticas[visitante]["Goles Contra"] += goles_local

        if goles_local > goles_visitante:
            estadisticas[local]["Ganados"] += 1
            estadisticas[visitante]["Perdidos"] += 1
            estadisticas[local]["Puntos"] += 3

        elif goles_local < goles_visitante:
            estadisticas[visitante]["Ganados"] += 1
            estadisticas[local]["Perdidos"] += 1
            estadisticas[visitante]["Puntos"] += 3

        else:
            estadisticas[local]["Empatados"] += 1
            estadisticas[visitante]["Empatados"] += 1
            estadisticas[local]["Puntos"] += 1
            estadisticas[visitante]["Puntos"] += 1

    return estadisticas

In [ ]:
#Prueba de uso
from pprint import pprint

p_crear_estadisticas = crear_estadisticas(p_crear_resultado)
pprint (p_crear_estadisticas)

{'Girona FC': {'Empatados': 1,
               'Ganados': 0,
               'Goles Contra': 2,
               'Goles Favor': 2,
               'Perdidos': 0,
               'Puntos': 1},
 'Granollers': {'Empatados': 0,
                'Ganados': 1,
                'Goles Contra': 0,
                'Goles Favor': 1,
                'Perdidos': 0,
                'Puntos': 3},
 'Manlleu': {'Empatados': 0,
             'Ganados': 0,
             'Goles Contra': 1,
             'Goles Favor': 0,
             'Perdidos': 1,
             'Puntos': 0},
 'Olot': {'Empatados': 1,
          'Ganados': 0,
          'Goles Contra': 2,
          'Goles Favor': 2,
          'Perdidos': 0,
          'Puntos': 1},
 'Terrassa': {'Empatados': 0,
              'Ganados': 1,
              'Goles Contra': 4,
              'Goles Favor': 5,
              'Perdidos': 0,
              'Puntos': 3},
 'Vilafranca': {'Empatados': 0,
                'Ganados': 0,
                'Goles Contra': 5,
                'Goles Favor': 4,
                'Perdidos': 1,
                'Puntos': 0}}

⚡ `crear_clasificacion()`

1. Recibe el diccionario de estadísticas
2. Lo convierte en un DataFrame
3. Convierte el nombre de cada clave del diccionario en la columna Equipo
4. Ordena los equipos por Puntos de mayor a menor
5. Devuelve el DataFrame de clasificación

In [ ]:
def crear_clasificacion (estadisticas):

  data_estadistica = pd.DataFrame.from_dict(estadisticas, orient='index')

  data_estadistica.index.name = "Equipo"

  estadisticas_ordenado = data_estadistica.sort_values(by= "Puntos", ascending=False)

  estadisticas_indice = estadisticas_ordenado.reset_index()

  return estadisticas_indice

In [ ]:
#Prueba de uso
p_crear_clasificacion = crear_clasificacion(p_crear_estadisticas)

print(p_crear_clasificacion)

       Equipo  Goles Favor  Goles Contra  Ganados  Empatados  Perdidos  Puntos
0  Granollers            1             0        1          0         0       3
1    Terrassa            5             4        1          0         0       3
2   Girona FC            2             2        0          1         0       1
3        Olot            2             2        0          1         0       1
4     Manlleu            0             1        0          0         1       0
5  Vilafranca            4             5        0          0         1       0

⚡ `obtener_destacados()`

1. Recibe un DataFrame
2. Hace calculos especificos:
    *   Equipo más goleador
    *   Equipo más goleado
6. Devuelve datos equipos, goles total

In [ ]:
def obtener_destacados(estadisticas_indice):

    max_goles = estadisticas_indice["Goles Favor"].max()

    equipos_goleadores = estadisticas_indice[
        estadisticas_indice["Goles Favor"] == max_goles
    ]["Equipo"].tolist()

    max_goles_contra = estadisticas_indice["Goles Contra"].max()

    equipos_goleados = estadisticas_indice[
        estadisticas_indice["Goles Contra"] == max_goles_contra
    ]["Equipo"].tolist()

    return equipos_goleadores, max_goles, equipos_goleados, max_goles_contra

In [ ]:
#Prueba de uso
p_obtener_destacados = obtener_destacados(p_crear_clasificacion)
print(p_obtener_destacados)

(['Terrassa'], 5, ['Vilafranca'], 5)

⚡ `mostrar_resultados_futbol()`

1. Recibe datos de equipos y total goles
2. Comprueba empates
3. Devuelve la información detallada

In [ ]:
def mostrar_resultados_futbol(
    equipos_goleadores,
    max_goles,
    equipos_goleados,
    max_goles_contra,
    estadisticas_indice):

    if len(equipos_goleadores) == 1:
        print(
            f"Máximo goleador: {equipos_goleadores[0]} "
            f"con {max_goles} goles marcados.")
    else:
        print(
            f"Máximos goleadores: {', '.join(equipos_goleadores)} "
            f"con {max_goles} goles marcados cada uno.")

    if len(equipos_goleados) == 1:
        print(
            f"Equipo más goleado: {equipos_goleados[0]} "
            f"con {max_goles_contra} goles recibidos.")
    else:
        print(
            f"Equipos más goleados: {', '.join(equipos_goleados)} "
            f"con {max_goles_contra} goles recibidos cada uno.")

    print("\nClasificación final:")

    for indice, equipo in enumerate(estadisticas_indice["Equipo"], start=1):
        print(f"{indice}. {equipo}")

In [ ]:
#Prueba de uso
p_crear_clasificacion = crear_clasificacion(p_crear_estadisticas)

p_mostrar_resultados_futbol = mostrar_resultados_futbol(["Terrassa"], "5", ["Vilafranca"], "5", p_crear_clasificacion)

Máximo goleador: Terrassa con 5 goles marcados.
Equipo más goleado: Vilafranca con 5 goles recibidos.

Clasificación final:
1. Granollers
2. Terrassa
3. Girona FC
4. Olot
5. Manlleu
6. Vilafranca

⚡ `main_futbol()`

1. Recibe un archivo .txt con resultados futbolísticos
2. Orquesta todas las funciones creadas
3. Oculta el indice del DataFrame
3. Muestra:
    *   DataFrame con todas las estadísticas y resultados
    *   Respuesta a las preguntas planteadas

In [ ]:
def main_futbol(archivo):

  lista_partidos = cargar_partidos(archivo)
  resultados_partidos = crear_resultado(lista_partidos)
  estadisticas_partidos = crear_estadisticas(resultados_partidos)
  clasificacion_general = crear_clasificacion(estadisticas_partidos)

  equipos_goleadores, max_goles, equipos_goleados, max_goles_contra = (
        obtener_destacados(clasificacion_general))

  mostrar_resultados_futbol(
      equipos_goleadores,
      max_goles,
      equipos_goleados,
      max_goles_contra,
      clasificacion_general)

  display(clasificacion_general.style.hide(axis="index"))

In [ ]:
#Prueba de uso
p_main_futbol = main_futbol("/content/prueba_partidos.txt")

Máximo goleador: Terrassa con 5 goles marcados.
Equipo más goleado: Vilafranca con 5 goles recibidos.

Clasificación final:
1. Granollers
2. Terrassa
3. Girona FC
4. Olot
5. Manlleu
6. Vilafranca

### 🏆 Resultado final

In [ ]:
#Activación de main_futbol con los datos del archivo .txt

resultados_finales_futbol = main_futbol("/content/historic partits.txt")

Máximo goleador: Figueres con 161 goles marcados.
Equipo más goleado: Vilafranca con 172 goles recibidos.

Clasificación final:
1. Girona FC
2. Llagostera
3. Sabadell
4. Cornellà
5. RCD Espanyol
6. Figueres
7. Lleida Esportiu
8. Terrassa
9. FC Barcelona
10. Vilafranca
11. Badalona
12. Nàstic de Tarragona
13. Reus Deportiu
14. Granollers
15. Olot
16. Sant Andreu
17. Manlleu
18. Cerdanyola
19. Prat
20. Europa

### 📝 Notas sobre el ejercicio

1. Se utilizó `pprint` en una de las pruebas de uso para mejorar la visualización de los diccionarios. Pero su uso no es necesario para la ejecución final del ejercicio.
2. Se descartó deliberadamente el uso de `return` en las funciones `mostrar_resultados()` y `main_futbol()`, para evitar duplicar o ensuciar la visualización en Colab. Si fuera necesario reutilizar posteriormente el resultado, bastaría con añadir un `return` con la variable que se necesite.
3. Se utilizó la librería `pandas` para trabajar con el archivo .txt y el manejo de los DataFrames necesarios.
4. Se decidió cargar los archivos temporalmente en `/content` para simplificar su uso en Colab. Si fuera necesario mantenerlos activos se podrían almacenar en Google Drive, montar la unidad en Colab y modificar la ruta de acceso.
5. Se utilizó IA como apoyo para agilizar el diseño de la lógica necesaria para acumular los goles y partidos por equipo.
6. Se contemplo la posibilidad de empates en las estadísticas destacadas, de forma que si varios equipos comparten el máximo de goles a favor o en contra, se muestran todos los equipos.
7. Se mantuvo `Equipo` como columna para evitar complicar ciertas funciones de cálculo y posterirmente se ocultó el índice en la presentación final.